### ISSUE TITLE
Tab-completing an empty command causes an empty packet exception

### ISSUE THREAD

**Issue by ghost** [PaperMC/Waterfall#109]
When i try to auto compleate command like /warp [TAB], / [TAB] happens this bug. :(
```
03:05:25 [GRAVE] [/79.55.94.9:4450|Dinnerbone] <-> DownstreamBridge <-> [KitPvP] - encountered exception
io.netty.handler.codec.CorruptedFrameException: Empty Packet!
    at net.md_5.bungee.protocol.Varint21FrameDecoder.decode(Varint21FrameDecoder.java:36)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:411)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1018)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:402)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:307)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
    at java.lang.Thread.run(Thread.java:745)
03:05:25 [INFORMAZIONI] [Dinnerbone] disconnected with: The server you were previously on went down, you have been connected to a fallback server

```

>bungee
03:08:35 [INFORMAZIONI] This server is running Waterfall version git:Waterfall-Bootstrap:1.11-SNAPSHOT:d4f1b6d:94 by md_5
03:08:36 [GRAVE] Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@17f9d882, id=0, owner=ru.pixelfine.announcer.Main@1c7696c6, task=ru.pixelfine.announcer.Main$1@79e4c792, delay=1000, period=120000, running=true) encountered an exception
java.lang.NullPointerException

**Comment by Janmm14** [comment]
Please include your craftbukkit/spigot server's version.

**Comment by ghost** [comment]
>ver
[16:37:34 INFO]: This server is running CraftBukkit version git-Spigot-21fe707-e1ebe52 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[16:37:34 INFO]: Checking version, please wait...
[16:37:35 INFO]: You are 545 version(s) behind

**Comment by Techcable** [comment]
Only issue with allowing the empty packets is that it makes you more vulnerable to a denial of service attack. Theoretically, we could just ignore it for 1.8.8, as it's the only version where this issue should occur.
