### ISSUE TITLE
Exception on Login

### ISSUE THREAD

**Issue by ghost** [PaperMC/Waterfall#11]
Nothing too serious, but using the latest build on login, Waterfall throws this exception. Nothing negative seems to happen, but I just thought I'd report it anyway.

```
11:54:17 [SEVERE] java.lang.Throwable: Using a io.netty.buffer.PooledUnsafeHeapByteBuf, not a direct byte buf!
11:54:17 [SEVERE]   at net.md_5.bungee.protocol.Varint21FrameDecoder.decode(Varint21FrameDecoder.java:70)
11:54:17 [SEVERE]   at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:387)
11:54:17 [SEVERE]   at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:245)
11:54:17 [SEVERE]   at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
11:54:17 [SEVERE]   at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
11:54:17 [SEVERE]   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
11:54:17 [SEVERE]   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
11:54:17 [SEVERE]   at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
11:54:17 [SEVERE]   at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
11:54:17 [SEVERE]   at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
11:54:17 [SEVERE]   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
11:54:17 [SEVERE]   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
11:54:17 [SEVERE]   at io.netty.handler.timeout.ReadTimeoutHandler.channelRead(ReadTimeoutHandler.java:152)
11:54:17 [SEVERE]   at io.netty.channel.ChannelHandlerInvokerUtil.invokeChannelReadNow(ChannelHandlerInvokerUtil.java:83)
11:54:17 [SEVERE]   at io.netty.channel.DefaultChannelHandlerInvoker.invokeChannelRead(DefaultChannelHandlerInvoker.java:154)
11:54:17 [SEVERE]   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
11:54:17 [SEVERE]   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:145)
11:54:17 [SEVERE]   at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:1078)
11:54:17 [SEVERE]   at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:117)
11:54:17 [SEVERE]   at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:527)
11:54:17 [SEVERE]   at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:484)
11:54:17 [SEVERE]   at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:398)
11:54:17 [SEVERE]   at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:370)
11:54:17 [SEVERE]   at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
11:54:17 [SEVERE]   at java.lang.Thread.run(Thread.java:745)
```

**Comment by minecrafter** [comment]
This is already a known bug that occurred in the old 1.7/1.8/1.9 Waterfall.

**Comment by ghost** [comment]
Gotcha, apologies about bringing up a duplicate issue then.

**Comment by ghost** [comment]
This issue hasn't been fixed right?

**Comment by Janmm14** [comment]
Actually I think its fiyed by using netty 4.1
