### ISSUE TITLE
Error on refreshing server list

### ISSUE THREAD

**Issue by Rushmead** [PaperMC/Waterfall#113]
Hey

I get this when refreshing my server list with my server on it:
``19:06:15 [WARNING] [/IPADDRESS:9975] <-> InitialHandler - IllegalStateException: void future ``

**Comment by lululombard** [comment]
Same thing, can't connect to the proxy with build [#96](https://ci.destroystokyo.com/job/Waterfall/96/).
I had to revert to the build [#95](https://ci.destroystokyo.com/job/Waterfall/95/) to fix this.

**Comment by RikoDEV** [comment]
I have the same error on latest build:
```
12:00:29 [SEVERE] Jan 16, 2017 12:00:29 PM io.netty.util.concurrent.AbstractEventExecutor safeExecute
WARNING: A task raised an exception. Task: net.md_5.bungee.connection.InitialHandler$6$1@7f55847
java.lang.IllegalStateException: void future
    at io.netty.channel.VoidChannelPromise.fail(VoidChannelPromise.java:178)
    at io.netty.channel.VoidChannelPromise.addListener(VoidChannelPromise.java:44)
    at io.netty.channel.VoidChannelPromise.addListener(VoidChannelPromise.java:24)
    at net.md_5.bungee.netty.ChannelWrapper.write(ChannelWrapper.java:54)
    at net.md_5.bungee.UserConnection$1.sendPacket(UserConnection.java:155)
    at net.md_5.bungee.UserConnection.setCompressionThreshold(UserConnection.java:629)
    at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:506)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:312)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by dwi** [comment]
Same here, build #95 is okay.
