### ISSUE TITLE
NoSuchElementException: packet-encoder - AbstractEventExecutor safeExecute

### ISSUE THREAD

**Issue by mibby** [PaperMC/Waterfall#115]
Waterfall dev 99 (MC 1.11.2)

```
11:47:56 [INFO] §9This server is running Waterfall version git:Waterfall-Bootstrap:1.11-SNAPSHOT:6844551:99 by md_5
11:48:00 [SEVERE] Jan 21, 2017 11:48:00 AM io.netty.util.concurrent.AbstractEventExecutor safeExecute
WARNING: A task raised an exception. Task: net.md_5.bungee.connection.InitialHandler$6$1@36fa3c47
java.util.NoSuchElementException: packet-encoder
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1080)
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:251)
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:240)
	at net.md_5.bungee.netty.ChannelWrapper.addBefore(ChannelWrapper.java:115)
	at net.md_5.bungee.netty.ChannelWrapper.setCompressionThreshold(ChannelWrapper.java:127)
	at net.md_5.bungee.UserConnection.setCompressionThreshold(UserConnection.java:630)
	at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:504)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:312)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jamierocks** [comment]
As per-usual: does this happen on BungeeCord?, and reproduction steps.

**Comment by mibby** [comment]
I'm not sure. I just upgraded from Waterfall dev 95 to 99, then noticed these NoSuchElementException errors starting to occur. The error has occurred 5 times thus far for me and always ~5-7 seconds after an InitialHandler has connected. Not after every connection, just randomly from different players.

I can swap over to BungeeCord and monitor the logs if you'd like me to see if it appears there. But as far as I can recall, this never use to occur on dev 95 of Waterfall. So could be a newer upstream merge problem or a recent change.

If I had to take a random shot in the dark, I would say it has to do with one of these Waterfall commits since they touch the InitialHandler.
https://github.com/WaterfallMC/Waterfall/commit/0285fa1808069e3c493cf2dc2611d7848e0d2a25
https://github.com/WaterfallMC/Waterfall/commit/228318425bfbd5dd58b5d023d893317fc23c49af

Especially with this somewhat related error with AbstractEventExecutor safeExecute?
https://github.com/WaterfallMC/Waterfall/issues/113#issuecomment-272832039

**Comment by Cobwebster** [comment]
We have the same thing happen to us, latest waterfall.

**Comment by mibby** [comment]
@jamierocks I can not seem to reproduce on Bungee, so I am assuming it is a problem somewhere with the commits I linked above. On Waterfall dev 99, had this error occur 58 times since I initially reported the problem.

```
21:59:56 [SEVERE] Jan 25, 2017 9:59:56 PM io.netty.util.concurrent.AbstractEventExecutor safeExecute
WARNING: A task raised an exception. Task: net.md_5.bungee.connection.InitialHandler$6$1@410cea9e
java.util.NoSuchElementException: packet-encoder
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1080)
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:251)
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:240)
	at net.md_5.bungee.netty.ChannelWrapper.addBefore(ChannelWrapper.java:115)
	at net.md_5.bungee.netty.ChannelWrapper.setCompressionThreshold(ChannelWrapper.java:127)
	at net.md_5.bungee.UserConnection.setCompressionThreshold(UserConnection.java:630)
	at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:504)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:418)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:312)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at java.lang.Thread.run(Thread.java:745)
```

---

Edit: Split into new ticket here for issue organization.
https://github.com/WaterfallMC/Waterfall/issues/117

**Comment by Maxetto** [comment]
Latest Waterfall, experiencing this issue too.

Saw on Internet Bungee fixed it in 2015, might aswell be a new issue...

**Comment by Techcable** [comment]
This is likely a problem with us using the async dns resolver. https://github.com/WaterfallMC/Waterfall/blob/master/BungeeCord-Patches/0040-Use-async-Netty-DNS-resolver.patch

**Comment by mibby** [comment]
@jamierocks Testing on BungeeCord dev 1225 for the last day or so, this error only managed to occur once when looking through the logs. 

```
22:07:50 [SEVERE] Feb 01, 2017 10:07:50 PM io.netty.util.concurrent.AbstractEventExecutor safeExecute
WARNING: A task raised an exception. Task: net.md_5.bungee.connection.InitialHandler$6$1@578d7956
java.util.NoSuchElementException: packet-encoder
	at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1080)
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:251)
	at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:240)
	at net.md_5.bungee.netty.ChannelWrapper.addBefore(ChannelWrapper.java:115)
	at net.md_5.bungee.netty.ChannelWrapper.setCompressionThreshold(ChannelWrapper.java:127)
	at net.md_5.bungee.UserConnection.setCompressionThreshold(UserConnection.java:613)
	at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:497)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)
```

I'm not sure why it occurs so frequently with Waterfall dev 99 (65 times for me). Presumably one of the commits I linked above may be isolating the actual problem more frequently? Not entirely sure. Would it be possible for you to add a bit of debug info that could help locate the problem?

**Comment by mibby** [comment]
Fixed upstream in BungeeCord. Will re-open if it is still a problem.
