### ISSUE TITLE
IndexOutOfBoundsException - checkReadableBytes0 / EntityMap

### ISSUE THREAD

**Issue by mibby** [PaperMC/Waterfall#129]
Waterfall dev 103
Paper dev 1079 (Spigot 1.11.2)

I was disguised as a baby chicken and just sitting in place at my spawn. Then I was disconnected from the server after some time randomly with this error in the Waterfall console. No client mods, on 1.11.2.

Upon reconnecting, my player entity was invisible. I had to disguise as something and then undisguise again for it to reappear.

```
20:58:15 [SEVERE] [/IP:PORT|playerthatisme] <-> DownstreamBridge <-> [server] - encountered exception
java.lang.IndexOutOfBoundsException: readerIndex(17) + length(1) exceeds writerIndex(17): PooledUnsafeDirectByteBuf(ridx: 17, widx: 17, cap: 17)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1396)
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:687)
	at net.md_5.bungee.entitymap.EntityMap.rewriteMetaVarInt(EntityMap.java:144)
	at net.md_5.bungee.entitymap.EntityMap_1_11.rewriteClientbound(EntityMap_1_11.java:152)
	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:120)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1017)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:394)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:299)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mibby** [comment]
Happened again, not disguised. Was force kicked off the server by Waterfall just running around.

```
21:38:23 [SEVERE] [/ip:port|player] <-> DownstreamBridge <-> [server] - encountered exception
java.lang.IndexOutOfBoundsException: readerIndex(17) + length(1) exceeds writerIndex(17): PooledUnsafeDirectByteBuf(ridx: 17, widx: 17, cap: 17)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1396)
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:687)
	at net.md_5.bungee.entitymap.EntityMap.rewriteMetaVarInt(EntityMap.java:144)
	at net.md_5.bungee.entitymap.EntityMap_1_11.rewriteClientbound(EntityMap_1_11.java:152)
	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:120)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1017)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:394)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:299)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Janmm14** [comment]
> ![image](https://cloud.githubusercontent.com/assets/3533175/24822822/9a4c22b8-1bf8-11e7-8230-6f929b2b239e.png)
https://github.com/SpigotMC/BungeeCord/issues/2111#issuecomment-292668034

**Comment by Techcable** [comment]
I should probably dump a text representation of the entity metadata when a decoding error occurs.
It seems like this is LibsDisguises' fault, but you should probably wait until we have enough information to give to @libraryaddict (or it turns out it's us after all).

**Comment by Techcable** [comment]
b5ed82d599efafa515dd52428130836e59ef32b2 adds a patch to dump the raw hex of a packet if entity rewriting fails.
Could you please reproduce the error with that and then give us the result?

**Comment by mibby** [comment]
Sure, I'll update tonight and provide the raw hex of the packet when the error occurs again.

**Comment by mibby** [comment]
Apologies, work took over my time over the weekend.

Testing Waterfall dev 105 to try and reproduce the error, there seems to be a memory leak in the patch. Started crashing after only a few minutes of uptime and only a dozen or so players online at the time.
http://paste.ubuntu.com/24353878/

With Waterfall dev 106 (patch in the fire-pit, assuming disabled), no memory leak as far as I can tell. So not  able to reproduce with a raw hex dump until the memory leak is fixed. :(
