### ISSUE TITLE
Exception in thread

### ISSUE THREAD

**Issue by Bolly12321** [PaperMC/Waterfall#140]
Hey I've been getting the issue below and am unsure on what is wrong. All my servers run perfectly then suddenly after a few hours everything times-out.

The log below shows the issue. I've looked around and found nothing so I hope maybe someone here could help me out.

`16:44:11 [SEVERE] Exception in thread "ForkJoinPool.commonPool-worker-0" 
16:44:11 [SEVERE] java.lang.OutOfMemoryError: unable to create new native thread
16:44:11 [SEVERE] 	at java.lang.Thread.start0(Native Method)
16:44:11 [SEVERE] 	at java.lang.Thread.start(Thread.java:717)
16:44:11 [SEVERE] 	at java.util.concurrent.ForkJoinPool.createWorker(ForkJoinPool.java:1486)
16:44:11 [SEVERE] 	at java.util.concurrent.ForkJoinPool.tryAddWorker(ForkJoinPool.java:1517)
16:44:11 [SEVERE] 	at java.util.concurrent.ForkJoinPool.deregisterWorker(ForkJoinPool.java:1609)
16:44:11 [SEVERE] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:167)
16:44:11 [SEVERE] Exception in thread "ForkJoinPool.commonPool-worker-3" 
16:44:11 [SEVERE] java.lang.OutOfMemoryError: unable to create new native thread
16:44:11 [SEVERE] 	at java.lang.Thread.start0(Native Method)
16:44:11 [SEVERE] 	at java.lang.Thread.start(Thread.java:717)
16:44:11 [SEVERE] 	at java.util.concurrent.ForkJoinPool.createWorker(ForkJoinPool.java:1486)
16:44:11 [SEVERE] 	at java.util.concurrent.ForkJoinPool.tryAddWorker(ForkJoinPool.java:1517)
16:44:11 [SEVERE] 	at java.util.concurrent.ForkJoinPool.deregisterWorker(ForkJoinPool.java:1609)
16:44:11 [SEVERE] 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:167)
16:44:11 [SEVERE] May 28, 2017 4:44:11 PM com.github.benmanes.caffeine.cache.BoundedLocalCache scheduleDrainBuffers
WARNING: Exception thrown when submitting maintenance task
java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method)
	at java.lang.Thread.start(Thread.java:717)
	at java.util.concurrent.ForkJoinPool.createWorker(ForkJoinPool.java:1486)
	at java.util.concurrent.ForkJoinPool.tryAddWorker(ForkJoinPool.java:1517)
	at java.util.concurrent.ForkJoinPool.signalWork(ForkJoinPool.java:1634)
	at java.util.concurrent.ForkJoinPool.externalPush(ForkJoinPool.java:2414)
	at java.util.concurrent.ForkJoinPool.execute(ForkJoinPool.java:2648)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.scheduleDrainBuffers(BoundedLocalCache.java:976)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.afterRead(BoundedLocalCache.java:815)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:1868)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:113)
	at com.github.benmanes.caffeine.cache.LocalLoadingCache.get(LocalLoadingCache.java:67)
	at me.lucko.luckperms.common.caching.UserCache.getPermissionData(UserCache.java:94)
	at me.lucko.luckperms.bungee.BungeeListener.onPlayerPermissionCheck(BungeeListener.java:177)
	at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
	at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:376)
	at net.md_5.bungee.UserConnection.hasPermission(UserConnection.java:510)
	at com.olivermartin410.plugins.ChatStream.buildFormat(ChatStream.java:139)
	at com.olivermartin410.plugins.ChatStream.sendMessage(ChatStream.java:86)
	at com.olivermartin410.plugins.Events.onChat(Events.java:291)
	at sun.reflect.GeneratedMethodAccessor33.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
	at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:376)
	at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:121)
	at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:50)
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:78)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:1017)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:394)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:299)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by jamierocks** [comment]
It seems as though you are running out of memory. I would discard this as being non-issue, but since I have seen reports of memory-leaks recently - how much have you given Waterfall?

**Comment by Bolly12321** [comment]
I have given it 1GB and here are my start-up parameters if that can help with the matter..

`command = "{JAVA}" -Xms1G -Xmx1G -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -XX:+UseStringDeduplication -jar Waterfall.jar nogui`

**Comment by jamierocks** [comment]
Well I guess with 1GB it may well have just run out of memory

**Comment by MarkTwoFive** [comment]
@Bolly12321 May you tell us how many (and what) plugins you've loaded, how many users were online and your Java version?

**Comment by Bolly12321** [comment]
Sure.

It happens throughout the day at random times. Happened with 25 players online earlier. Last night with 70+.

Plugins - https://i.gyazo.com/8fd10dbe58be07e177da9d4a6f2aae47.png

Java Version - 
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

What would you recommend I have my memory set to?

**Comment by Bolly12321** [comment]
Not sure if this may be of any help..
https://i.gyazo.com/b5ec7dcb286e0df0a2fb7026b5eb01b6.png

**Comment by MarkTwoFive** [comment]
@Bolly12321 Since I don't see anything particularly suspicious I'd recommend testing with 4G max and 1G min memory assignments. Monitor your proxies CPU und mem usage to see if that makes a difference.
If the memory space e.g. just steadily fills up regardless of users joining or leaving you may also just experience memory leaks as others reported.
