### ISSUE TITLE
NettiIO Error Log

### ISSUE THREAD

**Issue by JustZerooo** [PaperMC/Waterfall#158]
Minecraft Server Version : SpigotMC 1.12
System OS : Windows 10 x64
What i have modiefied : Only Strings (Lets look it a bit better as it is)

Error Log : 

```quote
11:34:46 [INFORMATION] Using standard Java JCE cipher.
11:34:46 [INFORMATION] Using standard Java compressor.
11:34:46 [INFORMATION] Enabled Travertine version git:Travertine-Bootstrap:1.12-SNAPSHOT:f5aad42:unknown
11:34:46 [INFORMATION] Couldn't detect bungee version. Custom build?
11:34:46 [INFORMATION] Loaded plugin reconnect_yaml version git:reconnect_yaml:1.12-SNAPSHOT:f5aad42:unknown by WaterfallMC
11:34:46 [INFORMATION] Loaded plugin cmd_find version git:cmd_find:1.12-SNAPSHOT:f5aad42:unknown by WaterfallMC
11:34:46 [INFORMATION] Loaded plugin cmd_server version git:cmd_server:1.12-SNAPSHOT:f5aad42:unknown by WaterfallMC
11:34:46 [INFORMATION] Loaded plugin cmd_alert version git:cmd_alert:1.12-SNAPSHOT:f5aad42:unknown by WaterfallMC
11:34:46 [INFORMATION] Loaded plugin cmd_send version git:cmd_send:1.12-SNAPSHOT:f5aad42:unknown by WaterfallMC
11:34:46 [INFORMATION] Loaded plugin cmd_list version git:cmd_list:1.12-SNAPSHOT:f5aad42:unknown by WaterfallMC
11:34:46 [WARNUNG] Forced host server pvp is not defined
11:34:46 [INFORMATION] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.12-SNAPSHOT:f5aad42:unknown by WaterfallMC
11:34:46 [INFORMATION] Enabled plugin cmd_find version git:cmd_find:1.12-SNAPSHOT:f5aad42:unknown by WaterfallMC
11:34:46 [INFORMATION] Enabled plugin cmd_server version git:cmd_server:1.12-SNAPSHOT:f5aad42:unknown by WaterfallMC
11:34:46 [INFORMATION] Enabled plugin cmd_alert version git:cmd_alert:1.12-SNAPSHOT:f5aad42:unknown by WaterfallMC
11:34:46 [INFORMATION] Enabled plugin cmd_send version git:cmd_send:1.12-SNAPSHOT:f5aad42:unknown by WaterfallMC
11:34:46 [INFORMATION] Enabled plugin cmd_list version git:cmd_list:1.12-SNAPSHOT:f5aad42:unknown by WaterfallMC
11:34:46 [INFORMATION] Listening on /127.0.0.1:25565
11:34:46 [INFORMATION] Started query on /127.0.0.1:25565
11:36:26 [INFORMATION] [/127.0.0.1:53207] <-> InitialHandler has connected
11:36:27 [INFORMATION] [Selecat|/127.0.0.1:53207] <-> ServerConnector [lobby] has connected
11:36:28 [SCHWERWIEGEND] java.lang.Throwable: Using a io.netty.buffer.PooledUnsafeHeapByteBuf, not a direct byte buf!
11:36:28 [SCHWERWIEGEND] 	at net.md_5.bungee.protocol.Varint21FrameDecoder.decode(Varint21FrameDecoder.java:64)
11:36:28 [SCHWERWIEGEND] 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
11:36:28 [SCHWERWIEGEND] 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
11:36:28 [SCHWERWIEGEND] 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
11:36:28 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
11:36:28 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
11:36:28 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
11:36:28 [SCHWERWIEGEND] 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
11:36:28 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
11:36:28 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
11:36:28 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
11:36:28 [SCHWERWIEGEND] 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
11:36:28 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
11:36:28 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
11:36:28 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
11:36:28 [SCHWERWIEGEND] 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
11:36:28 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
11:36:28 [SCHWERWIEGEND] 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
11:36:28 [SCHWERWIEGEND] 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
11:36:28 [SCHWERWIEGEND] 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
11:36:28 [SCHWERWIEGEND] 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
11:36:28 [SCHWERWIEGEND] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:579)
11:36:28 [SCHWERWIEGEND] 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:496)
11:36:28 [SCHWERWIEGEND] 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
11:36:28 [SCHWERWIEGEND] 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
11:36:28 [SCHWERWIEGEND] 	at java.lang.Thread.run(Unknown Source)
```

How to reproduce : 

Download your latest version, make a clean setup, install a SpigotMC Server, use the latest Dev Build from ProtocolSupport -> https://build.true-games.org/view/ProtocolSupport/job/ProtocolSupport/ and join with a ForgeMod 1.7.10 Client to the 1.12 Server!

**Comment by jamierocks** [comment]
This is not the place for support with Travertine.
