### ISSUE TITLE
Unexpected exception - CorruptedFrameException: not a response

### ISSUE THREAD

**Issue by mibby** [PaperMC/Waterfall#182]
Waterfall dev 152
PaperSpigot dev 1237

Has occurred 17 times for me thus far since updating builds.
```
[01:35:16] [Netty Worker IO Thread #13/WARN] [io.netty.resolver.dns.DnsNameResolver]: [id: 0xb48d2a67] Unexpected exception: 
io.netty.handler.codec.CorruptedFrameException: not a response
	at io.netty.handler.codec.dns.DatagramDnsResponseDecoder.newResponse(DatagramDnsResponseDecoder.java:84) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.handler.codec.dns.DatagramDnsResponseDecoder.decode(DatagramDnsResponseDecoder.java:57) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.handler.codec.dns.DatagramDnsResponseDecoder.decode(DatagramDnsResponseDecoder.java:33) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:480) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
[01:35:29] [Netty Worker IO Thread #13/WARN] [io.netty.resolver.dns.DnsNameResolver]: [id: 0xb48d2a67] Unexpected exception: 
io.netty.handler.codec.CorruptedFrameException: not a response
	at io.netty.handler.codec.dns.DatagramDnsResponseDecoder.newResponse(DatagramDnsResponseDecoder.java:84) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.handler.codec.dns.DatagramDnsResponseDecoder.decode(DatagramDnsResponseDecoder.java:57) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.handler.codec.dns.DatagramDnsResponseDecoder.decode(DatagramDnsResponseDecoder.java:33) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:480) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
```

**Comment by mibby** [comment]
Another error, possibly not related though.

```
[02:09:22] [Netty Worker IO Thread #5/ERROR]: [/ip:port|player] <-> DownstreamBridge <-> [EosCraft] - encountered exception
java.lang.NullPointerException: null
	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:463) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at net.md_5.bungee.protocol.packet.PluginMessage.handle(PluginMessage.java:75) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:103) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:797) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:11e9bbe:152]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
```
