### ISSUE TITLE
java.lang.Throwable: Using a io.netty.buffer.PooledUnsafeHeapByteBuf, not a direct byte buf!

### ISSUE THREAD

**Issue by mibby** [PaperMC/Waterfall#185]
Waterfall dev 152

Error occurs when I login to a local waterfall test environment on 1.12.2. My login does go through, but the error occurs.

```
[04:22:31] [Netty Worker IO Thread #0/ERROR]: java.lang.Throwable: Using a io.netty.buffer.PooledUnsafeHeapByteBuf, not a direct byte buf!
[04:22:31] [Netty Worker IO Thread #0/ERROR]: 	at net.md_5.bungee.protocol.Varint21FrameDecoder.decode(Varint21FrameDecoder.java:54)
[04:22:31] [Netty Worker IO Thread #0/ERROR]: 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
[04:22:31] [Netty Worker IO Thread #0/ERROR]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
[04:22:31] [Netty Worker IO Thread #0/ERROR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
[04:22:31] [Netty Worker IO Thread #0/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[04:22:31] [Netty Worker IO Thread #0/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[04:22:31] [Netty Worker IO Thread #0/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[04:22:31] [Netty Worker IO Thread #0/ERROR]: 	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
[04:22:31] [Netty Worker IO Thread #0/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[04:22:31] [Netty Worker IO Thread #0/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[04:22:31] [Netty Worker IO Thread #0/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[04:22:31] [Netty Worker IO Thread #0/ERROR]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[04:22:31] [Netty Worker IO Thread #0/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[04:22:31] [Netty Worker IO Thread #0/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[04:22:31] [Netty Worker IO Thread #0/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[04:22:31] [Netty Worker IO Thread #0/ERROR]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
[04:22:31] [Netty Worker IO Thread #0/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[04:22:31] [Netty Worker IO Thread #0/ERROR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[04:22:31] [Netty Worker IO Thread #0/ERROR]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
[04:22:31] [Netty Worker IO Thread #0/ERROR]: 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
[04:22:31] [Netty Worker IO Thread #0/ERROR]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
[04:22:31] [Netty Worker IO Thread #0/ERROR]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
[04:22:31] [Netty Worker IO Thread #0/ERROR]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
[04:22:31] [Netty Worker IO Thread #0/ERROR]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
[04:22:31] [Netty Worker IO Thread #0/ERROR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
[04:22:31] [Netty Worker IO Thread #0/ERROR]: 	at java.lang.Thread.run(Unknown Source)

```

**Comment by MarkTwoFive** [comment]
Yet another instance of an admin falling for the debugging trace that's supposed to be helpful.

Maybe at least change the Log Level from ``ERROR`` to ``DEBUG`` ....

**Comment by jamierocks** [comment]
Duplicate of #160.
