### ISSUE TITLE
io.netty.handler.codec.CorruptedFrameException: Empty Packet!

### ISSUE THREAD

**Issue by Luuzzi** [PaperMC/Waterfall#191]
```
18:39:43 [INFO] [/213.59.146.56:54630] <-> InitialHandler has connected
18:44:33 [INFO] [/213.59.146.56:54730] <-> InitialHandler has connected
18:44:55 [INFO] [/213.59.146.56:54742] <-> InitialHandler has connected
18:45:29 [INFO] [/213.59.146.56:54763] <-> InitialHandler has connected
18:53:31 [INFO] [/213.59.146.56:65127] <-> InitialHandler has connected
18:53:32 [INFO] [/213.59.146.56:65131] <-> InitialHandler has connected
18:53:33 [INFO] [/192.223.30.153:35334] <-> InitialHandler has connected
18:54:02 [WARNING] [/213.59.146.56:65131] <-> InitialHandler - read timed out
18:54:20 [SEVERE] [/78.93.43.51:52669] <-> InitialHandler - encountered exception
io.netty.handler.codec.CorruptedFrameException: Empty Packet!
	at net.md_5.bungee.protocol.Varint21FrameDecoder.decode(Varint21FrameDecoder.java:29)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:236)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:494)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:801)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
18:54:26 [WARNING] [/67.205.191.44:36045] <-> InitialHandler - NativeIoException: syscall:read(..) failed: Connection reset by peer
18:54:30 [WARNING] [/95.87.124.2:33672] <-> InitialHandler - read timed out
18:54:30 [WARNING] [/207.38.56.161:34435] <-> InitialHandler - read timed out
18:54:30 [WARNING] [/103.28.114.82:40864] <-> InitialHandler - read timed out
18:54:30 [WARNING] [/43.225.169.188:58072] <-> InitialHandler - read timed out
18:54:30 [WARNING] [/12.70.138.195:40939] <-> InitialHandler - read timed out
18:54:30 [WARNING] [/110.232.64.69:36057] <-> InitialHandler - read timed out
18:54:31 [WARNING] [/95.87.124.2:33684] <-> InitialHandler - read timed out
18:54:31 [WARNING] [/103.28.114.82:40866] <-> InitialHandler - read timed out
18:54:31 [WARNING] [/95.87.124.2:33688] <-> InitialHandler - read timed out
18:54:31 [WARNING] [/95.87.124.2:33689] <-> InitialHandler - read timed out
18:54:31 [WARNING] [/212.62.246.185:38889] <-> InitialHandler - read timed out
18:54:31 [WARNING] [/110.232.64.69:36068] <-> InitialHandler - read timed out
18:54:31 [WARNING] [/95.87.124.2:33693] <-> InitialHandler - read timed out
18:54:31 [WARNING] [/12.70.138.195:40942] <-> InitialHandler - read timed out
```

**Comment by Black-Hole** [comment]
A client sent an empty packet. It's safe to just ignore that exception.

**Comment by Luuzzi** [comment]
But i can't ping bungeecord (even handshake not displayed in the log) for a few minutes, after this error - when client send EmptyPacket, but when a few minutes passed - all OK. I don't know why, but it's REALLY so strange. Maybe it's netty issue? 

P.S: I didn't use any plugins when this is happened. Only small modification in InitialHandler.class - finish(); method. But this is handled after LoginSuccess packet, not before.
![6iyoxt_qtkac2nnzmble2g](https://user-images.githubusercontent.com/13926595/32925072-017cab6c-cb51-11e7-9854-24339b76bf8c.png)

**Comment by electronicboy** [comment]
> InitialHandler - read timed out

More looks like your network had a drop rather than a software issue

**Comment by Malachiel87** [comment]
same here, happen more times on creative server 1.12.2 with viaversion and rewind

**Comment by kamcio96** [comment]
@xion87 are you using plib? if so can you give plugin list?

**Comment by MatinHQ** [comment]
@electronicboy you told me something on your server is sending empty packet but i never had this problem on BungeeCord i recently join waterfall community and that problem happened to me!

**Comment by electronicboy** [comment]
We've not made any changes to the proxy which could cause this issue, I've looked over our changes around the areas at which this could even remotely occur and cannot see any potential for this.

Our closest lead is that it's down to plugins on the server somehow managing to send through empty packets towards the proxy, issues like this do exist with bungeecord as can be seen on their tracker which has lead towards the exact same resolution as ours. if you can provide actual steps to reproduce this issue which can be used to show that there is an actual issue on our side, we'll look into it, but I've personally never encountered this issue and everything I've been shown points elsewhere.
