### ISSUE TITLE
io.netty.handler.codec.DecoderException: Error decoding packet unknown with contents

### ISSUE THREAD

**Issue by martinlacorrona** [PaperMC/Waterfall#198]
`[20:13:16] [Netty Worker IO Thread #5/ERROR]: [/181.64.236.169:49460|lapeque123] <-> DownstreamBridge <-> [ctw1] - encountered exception
io.netty.handler.codec.DecoderException: Error decoding packet unknown with contents:

	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:68) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:82e5f37:164]
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:12) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:82e5f37:164]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:82e5f37:164]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:82e5f37:164]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:82e5f37:164]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:82e5f37:164]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:82e5f37:164]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:82e5f37:164]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:82e5f37:164]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:82e5f37:164]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:82e5f37:164]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:82e5f37:164]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:82e5f37:164]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:82e5f37:164]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:82e5f37:164]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:82e5f37:164]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:82e5f37:164]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:82e5f37:164]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:82e5f37:164]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:82e5f37:164]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:82e5f37:164]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:82e5f37:164]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:82e5f37:164]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:82e5f37:164]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:82e5f37:164]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:82e5f37:164]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:82e5f37:164]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(0) + length(1) exceeds writerIndex(0): UnpooledSlicedByteBuf(ridx: 0, widx: 0, cap: 0/0, unwrapped: PooledUnsafeDirectByteBuf(ridx: 2, widx: 2, cap: 64))
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1403) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:82e5f37:164]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:707) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:82e5f37:164]
	at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:108) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:82e5f37:164]
	at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:98) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:82e5f37:164]
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:39) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:82e5f37:164]
	... 27 `more``

**Comment by mikroskeem** [comment]
#178
