### ISSUE TITLE
UnknownHostException problem

### ISSUE THREAD

**Issue by m0bYczE** [PaperMC/Waterfall#199]
Hello, i have got a problem with UnknownHostException. For example, there is a error:
`[20:12:56 ERROR]: java.net.UnknownHostException: getmeproxy.com
[20:12:56 ERROR]:       at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[20:12:56 ERROR]:       at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[20:12:56 ERROR]:       at java.net.Socket.connect(Socket.java:589)
[20:12:56 ERROR]:       at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
[20:12:56 ERROR]:       at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
[20:12:56 ERROR]:       at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
[20:12:56 ERROR]:       at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
[20:12:56 ERROR]:       at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
[20:12:56 ERROR]:       at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
[20:12:56 ERROR]:       at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
[20:12:56 ERROR]:       at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
[20:12:56 ERROR]:       at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
[20:12:56 ERROR]:       at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
[20:12:56 ERROR]:       at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
[20:12:56 ERROR]:       at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
[20:12:56 ERROR]:       at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
[20:12:56 ERROR]:       at skinsrestorer.shared.utils.ProxyManager.readURL(ProxyManager.java:52)
[20:12:56 ERROR]:       at skinsrestorer.shared.utils.ProxyManager.updateProxies(ProxyManager.java:34)
[20:12:56 ERROR]:       at skinsrestorer.shared.utils.ProxyManager.getList(ProxyManager.java:25)
[20:12:56 ERROR]:       at skinsrestorer.shared.utils.MojangAPI.readURLProxy(MojangAPI.java:167)
[20:12:56 ERROR]:       at skinsrestorer.shared.utils.MojangAPI.getUUIDProxy(MojangAPI.java:118)
[20:12:56 ERROR]:       at skinsrestorer.shared.utils.MojangAPI.getUUID(MojangAPI.java:111)
[20:12:56 ERROR]:       at skinsrestorer.shared.storage.SkinStorage.getOrCreateSkinForPlayer(SkinStorage.java:108)
[20:12:56 ERROR]:       at skinsrestorer.bungee.SkinApplier$1.run(SkinApplier.java:25)
[20:12:56 ERROR]:       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[20:12:56 ERROR]:       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[20:12:56 ERROR]:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[20:12:56 ERROR]:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[20:12:56 ERROR]:       at java.lang.Thread.run(Thread.java:748)
`

Thank you for your help.

**Comment by electronicboy** [comment]
This is not a waterfall issue, this is either a plugin issue or an issue with your systems network configuration.

**Comment by Black-Hole** [comment]
Caused by SkinsRestorer

**Comment by m0bYczE** [comment]
I fixed the problem, i've set the google dns servers and it works prefect. Thanks :)
