### ISSUE TITLE
Netty warning spam

### ISSUE THREAD

**Issue by Sir-Will** [PaperMC/Waterfall#203]
hey,

is it possible that waterfall is causing this fix: https://github.com/MinecraftForge/MinecraftForge/pull/4363 to not work when connecting via waterfall to the forge server?

**Comment by jamierocks** [comment]
The issue title is "Netty Warning Spam", yet you haven't provided any logs to back this up.

**Comment by Sir-Will** [comment]
```
[18:08:20] [Netty Epoll Server IO #9/WARN] [io.netty.channel.DefaultChannelPipeline]: An exception was thrown by a user handler's exceptionCaught() method while handling the following exception:
java.io.IOException: Error while writev(...): Connection reset by peer
	at io.netty.channel.epoll.Native.$$YJP$$writevAddresses(Native Method) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.Native.writevAddresses(Native.java) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.EpollSocketChannel.writeBytesMultiple(EpollSocketChannel.java:184) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.EpollSocketChannel.doWriteMultiple(EpollSocketChannel.java:364) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.EpollSocketChannel.doWrite(EpollSocketChannel.java:317) ~[minecraft_server.1.10.2.jar:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:707) [minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:248) [minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.EpollSocketChannel$EpollSocketUnsafe.epollOutReady(EpollSocketChannel.java:623) [minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:322) [minecraft_server.1.10.2.jar:?]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:264) [minecraft_server.1.10.2.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [minecraft_server.1.10.2.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

**Comment by jamierocks** [comment]
I don't think a 'Connection reset by peer' exception would happen if that fix breaks waterfall - but I'd be interested to know if Waterfall throws any errors?

**Comment by Sir-Will** [comment]
Nothing out of the ordinary.
