### ISSUE TITLE
Console spam with LVS

### ISSUE THREAD

**Issue by caoli5288** [PaperMC/Waterfall#23]
LVS will open a alive check connection every 6s, in BungeeCord It print one-line error msg, but spam full stack-trace in waterfall.

```
    at io.netty.channel.DefaultChannelPipeline.fireExceptionCaught(DefaultChannelPipeline.java:1066)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.handleReadException(AbstractEpollStreamChannel.java:675)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:898)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:359)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:275)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:742)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Cannot get ID for packet class net.md_5.bungee.protocol.packet.Kick
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
    at net.md_5.bungee.protocol.Protocol$DirectionData.getId(Protocol.java:346)
    at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:23)
    at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:9)
    at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
    ... 58 more
```

Please fix it :-)

**Comment by minecrafter** [comment]
Already fixed, please update Waterfall.

**Comment by caoli5288** [comment]
@minecrafter I'm sorry. Your ci's last build like outdated (build at 03 Jun 16). Where can I get latest one except build from source?

**Comment by Techcable** [comment]
https://ci.aquifermc.org/

**Comment by caoli5288** [comment]
@Techcable THX
