### ISSUE TITLE
Error decoding packet class Handshake with contents

### ISSUE THREAD

**Issue by ygtdmn** [PaperMC/Waterfall#234]
```
[13:33:25] [Netty Worker IO Thread #15/ERROR]: [/125.141.200.38:33466] <-> InitialHandler - encountered exception
io.netty.handler.codec.DecoderException: Error decoding packet class Handshake with contents:
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 00                                              |.               |
+--------+-------------------------------------------------+----------------+
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:68) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:12) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): UnpooledSlicedByteBuf(ridx: 1, widx: 1, cap: 1/1, unwrapped: PooledUnsafeDirectByteBuf(ridx: 60, widx: 60, cap: 64))
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1405) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:707) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:108) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:98) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at net.md_5.bungee.protocol.packet.Handshake.read(Handshake.java:26) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at net.md_5.bungee.protocol.DefinedPacket.read(DefinedPacket.java:193) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:46) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	... 23 more
```

```
io.netty.handler.codec.DecoderException: Error decoding packet class Handshake with contents:
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 00 10 68 45 53 74 41 59 59 44 7a 37 48 7a 53 64 |..hEStAYYDz7HzSd|
|00000010| 45 71                                           |Eq              |
+--------+-------------------------------------------------+----------------+
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:68) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:12) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(3) + length(104) exceeds writerIndex(18): UnpooledSlicedByteBuf(ridx: 3, widx: 18, cap: 18/18, unwrapped: PooledUnsafeDirectByteBuf(ridx: 77, widx: 77, cap: 128))
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1405) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1392) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:872) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:880) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at net.md_5.bungee.protocol.DefinedPacket.readString(DefinedPacket.java:36) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at net.md_5.bungee.protocol.packet.Handshake.read(Handshake.java:27) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at net.md_5.bungee.protocol.DefinedPacket.read(DefinedPacket.java:193) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:46) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:1c35107:unknown]
	... 23 more
```

When a lot of spambot trying to join server i get this errors spamming in my console.

**Comment by Janmm14** [comment]
Spambots apparantly send wrong data and so just cause log spam instead of ingame spam.

**Comment by electronicboy** [comment]
The proxy is acting as intended, something is sending you invalid data, you're being told that something is sending invalid data.
