### ISSUE TITLE
IllegalArgumentException with entity from forge mod

### ISSUE THREAD

**Issue by Sir-Will** [PaperMC/Waterfall#237]
The mob Primordial Malevolence from The Betweenlands causes the error below in Waterfall.
Connecting to the server without Waterfall doesn't cause this issue.

This is with waterfall build 178, forge-1.12.2-14.23.4.2705 and spongeforge-1.12.2-2705-7.1.0-BETA-3172

```
[14:49:45] [Netty Worker IO Thread #1/ERROR]: [SirWill] <-> DownstreamBridge <-> [sponge7_test] - encountered exception
java.lang.IllegalArgumentException: Unknown meta type 15
	at net.md_5.bungee.entitymap.EntityMap.rewriteMetaVarInt(EntityMap.java:200) ~[Waterfall-B178.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at net.md_5.bungee.entitymap.EntityMap_1_12_1.rewriteClientbound(EntityMap_1_12_1.java:152) ~[Waterfall-B178.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:121) ~[Waterfall-B178.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:111) ~[Waterfall-B178.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall-B178.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall-B178.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall-B178.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [Waterfall-B178.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall-B178.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall-B178.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall-B178.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [Waterfall-B178.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall-B178.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall-B178.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall-B178.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [Waterfall-B178.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall-B178.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall-B178.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall-B178.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [Waterfall-B178.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297) [Waterfall-B178.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413) [Waterfall-B178.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [Waterfall-B178.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall-B178.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall-B178.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall-B178.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [Waterfall-B178.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall-B178.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall-B178.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall-B178.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [Waterfall-B178.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall-B178.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall-B178.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [Waterfall-B178.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808) [Waterfall-B178.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408) [Waterfall-B178.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308) [Waterfall-B178.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [Waterfall-B178.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:dd9c358:178]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

**Comment by MarkTwoFive** [comment]
Entity rewrites again. There're already a few closed issues about this. 
In order to resolve this a modification in the source code was necessary adding the unknown ID to the mappings if I remember correctly.

**Comment by electronicboy** [comment]
There really isn't much we can do about this, Bungeecord rewrites all entity IDs and as such requires rewriting the entire entity metadata for this, shamefully, when a mod registers it's own metadata types, we have no idea what they're doing and cannot see what they're doing with the data, or how to rewrite this properly.
There is an experimental bungee branch which appears to get rid of the rewrites, which if I get the time will look into porting to waterfall as a configurable option, in the meantime, there really isn't much that can be done.

**Comment by Sir-Will** [comment]
@electronicboy did you get a chance to look into it?

**Comment by electronicboy** [comment]
See #136

**Comment by Sir-Will** [comment]
Sounds like there are no news to this issue. Is there any way to see which entity is triggering this error?
