### ISSUE TITLE
Sometimes see this error on console (build 180)

### ISSUE THREAD

**Issue by netherstar** [PaperMC/Waterfall#238]
```
[20:16:34] [Netty Worker IO Thread #15/ERROR]: [/115.78.113.52:49828] <-> InitialHandler - encountered exception
io.netty.handler.codec.DecoderException: Error decoding packet class Handshake with contents:
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 00 06 74 61 6d 31 32 33                         |..tam123        |
+--------+-------------------------------------------------+----------------+
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:68) ~[Waterfall-180.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:3784a85:180]
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:12) ~[Waterfall-180.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:3784a85:180]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[Waterfall-180.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:3784a85:180]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall-180.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:3784a85:180]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall-180.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:3784a85:180]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall-180.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:3784a85:180]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [Waterfall-180.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:3784a85:180]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [Waterfall-180.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:3784a85:180]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall-180.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:3784a85:180]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall-180.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:3784a85:180]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall-180.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:3784a85:180]
	at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:236) [Waterfall-180.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:3784a85:180]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:494) [Waterfall-180.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:3784a85:180]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) [Waterfall-180.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:3784a85:180]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [Waterfall-180.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:3784a85:180]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall-180.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:3784a85:180]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall-180.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:3784a85:180]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall-180.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:3784a85:180]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [Waterfall-180.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:3784a85:180]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall-180.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:3784a85:180]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall-180.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:3784a85:180]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [Waterfall-180.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:3784a85:180]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [Waterfall-180.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:3784a85:180]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [Waterfall-180.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:3784a85:180]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [Waterfall-180.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:3784a85:180]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [Waterfall-180.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:3784a85:180]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808) [Waterfall-180.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:3784a85:180]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408) [Waterfall-180.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:3784a85:180]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308) [Waterfall-180.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:3784a85:180]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [Waterfall-180.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:3784a85:180]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(3) + length(116) exceeds writerIndex(8): UnpooledSlicedByteBuf(ridx: 3, widx: 8, cap: 8/8, unwrapped: PooledUnsafeDirectByteBuf(ridx: 9, widx: 9, cap: 9))
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1405) ~[Waterfall-180.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:3784a85:180]
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1392) ~[Waterfall-180.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:3784a85:180]
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:872) ~[Waterfall-180.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:3784a85:180]
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:880) ~[Waterfall-180.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:3784a85:180]
	at net.md_5.bungee.protocol.DefinedPacket.readString(DefinedPacket.java:36) ~[Waterfall-180.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:3784a85:180]
	at net.md_5.bungee.protocol.packet.Handshake.read(Handshake.java:27) ~[Waterfall-180.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:3784a85:180]
	at net.md_5.bungee.protocol.DefinedPacket.read(DefinedPacket.java:193) ~[Waterfall-180.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:3784a85:180]
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:46) ~[Waterfall-180.jar:git:Waterfall-Bootstrap:1.12-SNAPSHOT:3784a85:180]
	... 30 more
```

**Comment by jamierocks** [comment]
That's intended behaviour, and has been around for much longer than build 180. Someone is sending your server invalid data.
