### ISSUE TITLE
TerminalConsole IllegalStateException since build 181

### ISSUE THREAD

**Issue by Drc-DEV** [PaperMC/Waterfall#242]
This error pops up from time to time when opening the Waterfall console, this has been happening since build 181, and I think is related to the latest commit (6ae4356). When performing console commands, it goes unresponsive and comes back to life randomly. Please fix. (System OS Debian 9, Java 8)

> 2018-07-02 05:22:31,913 Log4j2-TF-2-AsyncLoggerConfig--2 ERROR An exception occurred processing Appender TerminalConsole java.lang.IllegalStateException
        at org.jline.reader.impl.LineReaderImpl.callWidget(LineReaderImpl.java:651)
        at net.minecrell.terminalconsole.TerminalConsoleAppender.append(TerminalConsoleAppender.java:265)
        at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
        at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
        at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:448)
        at org.apache.logging.log4j.core.async.AsyncLoggerConfig.asyncCallAppenders(AsyncLoggerConfig.java:115)
        at org.apache.logging.log4j.core.async.AsyncLoggerConfigDisruptor$Log4jEventWrapperHandler.onEvent(AsyncLoggerConfigDisruptor.java:111)
        at org.apache.logging.log4j.core.async.AsyncLoggerConfigDisruptor$Log4jEventWrapperHandler.onEvent(AsyncLoggerConfigDisruptor.java:97)
        at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:129)
        at java.lang.Thread.run(Thread.java:748)

**Comment by stephan-gh** [comment]
Not sure how this is related to 6ae4356. This is probably the same as https://github.com/WaterfallMC/Waterfall/issues/188 but I still haven't managed to reproduce it reliably. It shouldn't happen all the time.

Are you using some sort of control panel, terminal multiplexer (screen, tmux, ...), or does this even happen in a plain console session? Does it happen for each command?

**Comment by Drc-DEV** [comment]
I tried with glist and bungee, I'm using screen as terminal. It happens randomly but it's really frequent. Example: I type "bungee", I get feedback, type again a few times, don't get feedback, then randomly I get feedback again and so on. Or with "glist" sometimes it throws the error and prints half of the servers, if repeated then prints 1/4 of the servers, then nothing, after some tries it prints the whole list again and so on.

**Comment by stephan-gh** [comment]
I was able to reproduce this after quite a few tries, although not reliably. I will try to come up with a fix as soon as I have time.

**Comment by Drc-DEV** [comment]
I hope you get it to work soon, it's kinda annoying, and downgrading to a lower version is not a suitable option for me. Thanks anyways.

**Comment by MarkTwoFive** [comment]
> downgrading to a lower version is not a suitable option for me

Especially with that on-start delay that would be punishing you for using a version that still works fine ^^

**Comment by Janmm14** [comment]
> Especially with that on-start delay that would be punishing you for using a version that still works fine
>
> by @MarkL4YG 

That can be turned off with -DIReallyKnowWhatIAmDoingISwear command line flag

**Comment by jamierocks** [comment]
> I hope you get it to work soon, it's kinda annoying, and downgrading to a lower version is not a suitable option for me. Thanks anyways.

If you revert back a previous build, you won't be missing out on anything - unless you were effected by the issues that were resolved by that build. You'll be completely up-to-date, and the build was made recently enough that you won't get the "Out-of-date build warning".

I'd like to apologies for this regression, though I won't say that it was avoidable - it wasn't, as you've said "this error pops up from time to time". There are occasionally unforeseen bugs in software and this is one of them. That said, minecrell is a top guy and I know from many years of knowing him that this will be resolved as swiftly as it possibly can.

**Comment by Drc-DEV** [comment]
I'm not complaining. I trust minecrell and I hope the bug will be fixed soon. That's it. :)

**Comment by Drc-DEV** [comment]
This bug is indeed fixed now
