### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by MatinHQ** [PaperMC/Waterfall#267]
```
[07:27:53 ERROR]: [/95.38.154.190:13806|richnotch] <-> DownstreamBridge <-> [KitPVP] - encountered exception
io.netty.handler.codec.CorruptedFrameException: Empty Packet!
        at net.md_5.bungee.protocol.Varint21FrameDecoder.decode(Varint21FrameDecoder.java:36) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:eeda6d8:205]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:eeda6d8:205]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:eeda6d8:205]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:eeda6d8:205]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:eeda6d8:205]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:eeda6d8:205]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:eeda6d8:205]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:eeda6d8:205]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:eeda6d8:205]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:eeda6d8:205]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:eeda6d8:205]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:eeda6d8:205]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:eeda6d8:205]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:eeda6d8:205]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:eeda6d8:205]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:eeda6d8:205]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:eeda6d8:205]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:eeda6d8:205]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:eeda6d8:205]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
```

**Comment by MarkTwoFive** [comment]
Duplicate of #191 ?

**Comment by MatinHQ** [comment]
i didn't think so, because i can connect to server and ... i just saw this error and decide to report for community improvements

**Comment by MatinHQ** [comment]
that was going make some issues for example after this error redirect player to fallback server

**Comment by electronicboy** [comment]
Duplicate of #191 
Something on your server sent an empty packet somewhere
