### ISSUE TITLE
Unexpected packet received during server login process

### ISSUE THREAD

**Issue by dieterblancke** [PaperMC/Waterfall#285]
The following error occurs when people are trying to join our lobby (first they get sent to a Login Server, that server then sends them to the lobby):
```
java.lang.IllegalArgumentException: Unexpected packet received during server login process!
0d00
	at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:157) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:111) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

```
java.lang.IllegalArgumentException: Unexpected packet received during server login process!
4100
	at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:157) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:111) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
```

In the lobbies people get kicked for "Connection reset by peer".

Waterfall version git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223 by md_5

This is a pretty important issue, as hundreds of players encounter this issue, making them not able to join nor play.

**Comment by electronicboy** [comment]
You have a plugin on your actual servers which is causing invalid data to be sent

duplicate of #265

**Comment by dieterblancke** [comment]
Then I do wonder how it suddenly happened, because the only thing that changed is Waterfall being updated.

I assume it must be a plugin like ProtocolSupport then.

**Comment by dieterblancke** [comment]
@electronicboy I do think it is something related with Waterfall, as switching back to the regular (md_5) BungeeCord fixed this issue.

(this without any other changes done)

**Comment by electronicboy** [comment]
This exact issue has been duplicated on bungeecords' issue tracker too, this is definitely not a waterfall specific issue, and having been through our patches, we make no changes that would impact this directly, knowing the server and the proxy code, this does leave me at some level of confusion;

Do you have any plugins on the proxy itself? if you do, could you test if this has any changes?
Do you have any plugins on the server itself, such as protocol hacks or plugins which use ProtocolLib? if so, could you test if affected users are able to connect to a dev server or something with those plugins, and if removing them solves the issue?

I have a few theories, but working with both bungee and paper, I cannot see the potential for this to arise outside of plugin interaction

**Comment by dieterblancke** [comment]
Let me say it different, as reading back I didn't explain it properly.

The error only occurs on Waterfall (did not test Travertine nor Hexagon) while on BungeeCord it does not show.
However, players are still having the connection issue, it seems to mostly happen when they join our Lobbies having a considerably bad internet connection.

**Comment by electronicboy** [comment]
Closing, this was determined long ago to be solely down to the server sending invalid traffic, if somebody is seeing this issue, try replicating without any plugins/mods on the server.

**Comment by t0mi-dev** [comment]
.

**Comment by Guns29** [comment]
Hello I know this thread is old but i just started to have this problem this had to do with plugins sending misinformation to bungee here is what cause the problems 1. dicefurniture 2. Protectionlib 3.ProtocolLib after removing these the server started to work fine not sure why this happens but yea its crazy

**Comment by Chew** [comment]
If you are having this problem on a supported version, please make a new issue and follow the template.

**Comment by legendcuzican13** [comment]
Instead of the error shown at the top of this issue, I get this instead: `[04:17:12 ERROR]: [/127.0.0.1:55440] <-> InitialHandler - encountered exception: net.md_5.bungee.util.QuietException: Unexpected packet received during login process! 4554202f20485454502f312e310d0a48` . (I've removed protocol lib and disabled protocol lib stuff in all my plugins)

**Comment by xism4** [comment]
> Instead of the error shown at the top of this issue, I get this instead: `[04:17:12 ERROR]: [/127.0.0.1:55440] <-> InitialHandler - encountered exception: net.md_5.bungee.util.QuietException: Unexpected packet received during login process! 4554202f20485454502f312e310d0a48` . (I've removed protocol lib and disabled protocol lib stuff in all my plugins)

See the logs from the server. All i can see there is that you received an unexcepted packet during login.

Make sure to properly config ip_forwarding, read logs, reproduce without plugins on a vanilla ecosystem.

**Comment by legendcuzican13** [comment]
> > Instead of the error shown at the top of this issue, I get this instead: `[04:17:12 ERROR]: [/127.0.0.1:55440] <-> InitialHandler - encountered exception: net.md_5.bungee.util.QuietException: Unexpected packet received during login process! 4554202f20485454502f312e310d0a48` . (I've removed protocol lib and disabled protocol lib stuff in all my plugins)
> 
> See the logs from the server. All i can see there is that you received an unexcepted packet during login.
> 
> Make sure to properly config ip_forwarding, read logs, reproduce without plugins on a vanilla ecosystem.

Alright, I found that it works just fine without any plugins.  I've also removed all plugins that use protocollib. However, I still get the same error when players try to join. As for ip_forwarding, how could I better do that so that this issue stops?

**Comment by legendcuzican13** [comment]
![Screenshot 2023-01-08 10 23 13 AM](https://user-images.githubusercontent.com/108838775/211207641-8c97955d-8fa8-4344-b978-ab6fdb77bf02.png)
Here's a list of my plugins if that could help.

**Comment by Janmm14** [comment]
ProtocolLib is not the only plugin interacting with packets.
HamsterAPI, Citizens, Orebfuscator and maybe some more on your list also use packets.

**Comment by legendcuzican13** [comment]
Alright, Ill try removing some of those and test it out. Thanks

**Comment by legendcuzican13** [comment]
No success, I'll just try removing all the plugins 1 by one and see if I can find the problematic one.
