### ISSUE TITLE
Bungee Error

### ISSUE THREAD

**Issue by Jay9519** [PaperMC/Waterfall#289]
[00:00:04] [Netty Worker IO Thread #0/WARN]: Error whilst handling query packet from null
java.lang.IllegalStateException: No session!
	at net.md_5.bungee.query.QueryHandler.channelRead0(QueryHandler.java:88) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at net.md_5.bungee.query.QueryHandler.channelRead0(QueryHandler.java:26) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:483) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:adc5dcd:223]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]

I get this error every 5 minutes about 10-15 times in a row

**Comment by electronicboy** [comment]
This error is from clients connecting to your servers query port and sending invalid data

**Comment by Jay9519** [comment]
Is there a way to prevent this clogging up the bungee console logs?

**Comment by Janmm14** [comment]
Disable query if you don't need it.
