### ISSUE TITLE
Waterfall 1.13.2 build Clients are disconnected -

### ISSUE THREAD

**Issue by Narimm** [PaperMC/Waterfall#296]
This is the stack trace we are getting with old clients on a the waterfall build based around the 1.13.2 release.

I apologise we are not using the official builds as we have some custom api's we add in the build for our own purposes but those affect only tablist handling and a packet monitor api.  

The behaviour we are seeing is older clients cannot connect to older spigot servers(paper) using this particular waterfall build if we roll back to the previous build without the 1.13.2 commits it seems fine.

Obviously its possible this is a downstream issue. we are running protocolsupport on some of our older servers but its certainly only an issue since we rebased against the 23 Oct commits
```
at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:158) ~[waterfall-26.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:7d0b23b:26]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:111) ~[waterfall-26.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:7d0b23b:26]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[waterfall-26.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:7d0b23b:26]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[waterfall-26.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:7d0b23b:26]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[waterfall-26.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:7d0b23b:26]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[waterfall-26.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:7d0b23b:26]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[waterfall-26.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:7d0b23b:26]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[waterfall-26.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:7d0b23b:26]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[waterfall-26.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:7d0b23b:26]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[waterfall-26.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:7d0b23b:26]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[waterfall-26.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:7d0b23b:26]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[waterfall-26.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:7d0b23b:26]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[waterfall-26.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:7d0b23b:26]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[waterfall-26.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:7d0b23b:26]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[waterfall-26.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:7d0b23b:26]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426) ~[waterfall-26.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:7d0b23b:26]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[waterfall-26.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:7d0b23b:26]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[waterfall-26.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:7d0b23b:26]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[waterfall-26.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:7d0b23b:26]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[waterfall-26.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:7d0b23b:26]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall-26.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:7d0b23b:26]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[waterfall-26.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:7d0b23b:26]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[waterfall-26.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:7d0b23b:26]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[waterfall-26.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:7d0b23b:26]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[waterfall-26.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:7d0b23b:26]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[waterfall-26.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:7d0b23b:26]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[waterfall-26.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:7d0b23b:26]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[waterfall-26.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:7d0b23b:26]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799) ~[waterfall-26.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:7d0b23b:26]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:421) ~[waterfall-26.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:7d0b23b:26]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:321) ~[waterfall-26.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:7d0b23b:26]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) ~[waterfall-26.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:7d0b23b:26]
```

**Comment by Narimm** [comment]
When I say older spigot I mean 1.12.2

**Comment by electronicboy** [comment]
You're missing the most important section of the exception

**Comment by Narimm** [comment]
[20:12:03] [Netty Worker IO Thread #34/ERROR]: [Kasii_Startail|/58.174.166.8:55301] <-> ServerConnector [hub] - encountered exception

**Comment by Narimm** [comment]
finishes with
[20:12:03] [Netty Worker IO Thread #34/INFO]: [Kasii_Startail|/58.174.166.8:55301] <-> ServerConnector [hub] has disconnected

**Comment by Narimm** [comment]
Additional information it only occured on servers that had a SIDEBOARD of some sort installed .ie Featherboard.  and Is stable and does not occur on builds prior to the 23 October commits

**Comment by Janmm14** [comment]
> [20:12:03] [Netty Worker IO Thread #34/ERROR]: [Kasii_Startail|/58.174.166.8:55301] <-> ServerConnector [hub] - encountered exception

What's directly below this line?

**Comment by electronicboy** [comment]
Closing, as I'm pretty convinced that this is going to be down to your fork, specifically this commit: https://github.com/Narimm/waterfall-build/commit/cfe4882eeb4bff3a48f7bc8e8f73b96dc0f90a2f
which will fail on older client versions due to the fact that older servers send plain strings, as opposed to a json chat component, which will throw an exception with how you're handling it, you need to handle older clients accordingly

**Comment by Narimm** [comment]
Look thanks for the suggested direction - I will certainly look into it

The only thing that doesnt make a lot of sense is that we have been running that patch for over 2 years - against Bungeecord and we migrated it to Waterfall when we switched... the issue is speciifically occuring when we moved to the 23 Oct Version....we are now rolled back to the 1.13.1 Waterfall version with the same commit in place...and there is no problem.

**Comment by electronicboy** [comment]
The least you could do is provide the full stack trace, the only useful information I've received from you so far is that you're not even running our software and are using plugins which we provide no support for in any capacity.

**Comment by Narimm** [comment]
Look I am sorry  - I never asked your support of a plugin - if I believed a Bungee plugin was the cause I would never have come here.  I was really clear that I had forked your fork of bungeecord.   I have no intention of sitting here expecting  for you to fix it either.      I made it clear from the start that the issue only occured on Spigot Servers that had used a plugin that was sending packets relating to scoreboards.   As a result I reviewed the log again ....here is another Stacktrace - very different from the first that may be more pertinent.
```
[06:55:00] [Netty Worker IO Thread #44/ERROR]: [/70.173.194.59:60666|vegasvic1965] <-> DownstreamBridge <-> [prison] - encountered exception
java.lang.IllegalArgumentException: Team ^ANOCOLLIDE already exists in this scoreboard
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[waterfall-25.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ecfb959:25]
        at net.md_5.bungee.api.score.Scoreboard.addTeam(Scoreboard.java:73) ~[waterfall-25.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ecfb959:25]
        at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:208) ~[waterfall-25.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ecfb959:25]
        at net.md_5.bungee.protocol.packet.Team.handle(Team.java:122) ~[waterfall-25.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ecfb959:25]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:103) ~[waterfall-25.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ecfb959:25]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[waterfall-25.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ecfb959:25]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[waterfall-25.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ecfb959:25]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[waterfall-25.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ecfb959:25]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[waterfall-25.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ecfb959:25]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[waterfall-25.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ecfb959:25]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[waterfall-25.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ecfb959:25]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[waterfall-25.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ecfb959:25]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[waterfall-25.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ecfb959:25]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[waterfall-25.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ecfb959:25]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[waterfall-25.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ecfb959:25]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[waterfall-25.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ecfb959:25]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[waterfall-25.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ecfb959:25]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) ~[waterfall-25.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ecfb959:25]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[waterfall-25.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ecfb959:25]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[waterfall-25.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ecfb959:25]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[waterfall-25.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ecfb959:25]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall-25.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ecfb959:25]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[waterfall-25.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ecfb959:25]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[waterfall-25.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ecfb959:25]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[waterfall-25.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ecfb959:25]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[waterfall-25.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ecfb959:25]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[waterfall-25.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ecfb959:25]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[waterfall-25.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ecfb959:25]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[waterfall-25.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ecfb959:25]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799) ~[waterfall-25.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ecfb959:25]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:421) ~[waterfall-25.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ecfb959:25]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:321) ~[waterfall-25.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ecfb959:25]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) ~[waterfall-25.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:ecfb959:25]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[06:55:00] [Netty Worker IO Thread #44/INFO]: [/70.173.194.59:60666|vegasvic1965] <-> DownstreamBridge <-> [prison] has disconnected
```

**Comment by Narimm** [comment]
Oh and I took your advice and put in place some handling for that json code 

Thanks

**Comment by electronicboy** [comment]
The exception is caused because a server is trying to define a team that already exists, bungeecord currently has an issue in its scoreboard handling which means that scoreboard names cannot be re-used until the client has fully connected to the new server and bungee has cleared up some information
