### ISSUE TITLE
Randomly Disconnecting - Empty Packet

### ISSUE THREAD

**Issue by James76931** [PaperMC/Waterfall#301]
Hi, on Waterfall build 234 I'm being randomly disconnected for 'The server you were previously on went down, you have been connected to a fallback server.' Here is the error below, I have allow_empty_packets set to false.

`[13:52:45] [Netty Worker IO Thread #0/ERROR]: [/REDACTED:50965|James76931] <-> DownstreamBridge <-> [main] - encountered exception
io.netty.handler.codec.CorruptedFrameException: Empty Packet!
	at net.md_5.bungee.protocol.Varint21FrameDecoder.decode(Varint21FrameDecoder.java:43) ~[minecraft_server.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d91c0dd:234]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) ~[minecraft_server.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d91c0dd:234]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[minecraft_server.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d91c0dd:234]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[minecraft_server.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d91c0dd:234]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[minecraft_server.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d91c0dd:234]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[minecraft_server.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d91c0dd:234]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[minecraft_server.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d91c0dd:234]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[minecraft_server.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d91c0dd:234]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[minecraft_server.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d91c0dd:234]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[minecraft_server.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d91c0dd:234]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[minecraft_server.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d91c0dd:234]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[minecraft_server.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d91c0dd:234]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[minecraft_server.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d91c0dd:234]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[minecraft_server.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d91c0dd:234]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[minecraft_server.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d91c0dd:234]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799) ~[minecraft_server.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d91c0dd:234]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:421) ~[minecraft_server.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d91c0dd:234]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:321) ~[minecraft_server.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d91c0dd:234]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) ~[minecraft_server.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:d91c0dd:234]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
[13:52:45] [Netty Worker IO Thread #0/INFO]: [James76931] disconnected with: The server you were previously on went down, you have been connected to a fallback server
[13:52:45] [Netty Worker IO Thread #0/INFO]: [/REDACTED:50965|James76931] <-> DownstreamBridge <-> [main] has disconnected
[13:52:45] [Netty Worker IO Thread #0/INFO]: [/REDACTED:50965|James76931] -> UpstreamBridge has disconnected`

**Comment by James76931** [comment]
Never mind, setting empty packets to true seems to have fixed the issue.

**Comment by James76931** [comment]
Actually seems to still be an issue even with that set to true, does anyone have any ideas? I've just noticed it only seems to be happening when autocompleting commands in 1.13.
