### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by x1p** [PaperMC/Waterfall#306]
Saw this error happening with 2 different players

```
[07:54:47] [Netty Worker IO Thread #31/INFO]: [TestPlayer123|/123.123.123.123:55556] <-> ServerConnector [Lobby] has connected
[07:54:47] [Netty Worker IO Thread #31/WARN]: No client connected for pending server!
[07:54:47] [Netty Worker IO Thread #31/ERROR]: [TestPlayer123|/123.123.123.123:55556] <-> ServerConnector [Lobby] - encountered exception
java.lang.IllegalArgumentException: Unexpected packet received during server login process!
0d01
at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:157) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:111) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:421) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:321) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:c6a72d4:237]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[07:54:47] [Netty Worker IO Thread #31/INFO]: [TestPlayer123|/123.123.123.123:55556] <-> ServerConnector [Lobby] has disconnected
```

**Comment by Janmm14** [comment]
This can happen if a player puts the ip with port 25565 into a web browser

**Comment by x1p** [comment]
These 2 players which had this error did not do that for sure. Maybe someone else, but other than that: not a chance.

**Comment by electronicboy** [comment]
This error is generally caused by invalid traffic being sent to the server, or by plugins messing with packets causing a breakage
