### ISSUE TITLE
MOTD is glitched

### ISSUE THREAD

**Issue by SwegBusterr** [PaperMC/Waterfall#313]
https://images-ext-2.discordapp.net/external/8HeIdvmdD6nM59auArGkRSrzq8SpzKKhTO6h3d--KZU/https/i.gyazo.com/thumb/1200/83354c60ec4aa017cb7baf1d5bff7442-png.jpg?width=1202&height=212

It turns out that it is doing this, but I am still able to connect.

I am getting an error in console with

 `[23:51:38 WARN] [io.netty.channel.ChannelInitializer]: Failed to initialize a channel. Closing: [id: 0x00d1ff58]
java.lang.IllegalArgumentException: handler
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
at net.md_5.bungee.netty.HandlerBoss.setHandler(HandlerBoss.java:33) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
at protocolsupport.injector.BungeeNettyChannelInjector$CustomHandlerBoss.setHandler(BungeeNettyChannelInjector.java:92) ~[?:?]
at protocolsupport.injector.BungeeNettyChannelInjector$CustomHandlerBoss.<init>(BungeeNettyChannelInjector.java:86) ~[?:?]
at protocolsupport.injector.BungeeNettyChannelInjector$ChannelInitializerEntryPoint.initChannel(BungeeNettyChannelInjector.java:50) ~[?:?]
at protocolsupport.utils.netty.ChannelInitializer.channelRegistered(ChannelInitializer.java:17) ~[?:?]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:149) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:135) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:128) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRegistered(DefaultChannelPipeline.java:1407) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:149) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:135) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:859) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:513) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
at io.netty.channel.AbstractChannel$AbstractUnsafe.access$200(AbstractChannel.java:423) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:482) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:326) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

[23:51:38 WARN]: Error pinging remote server
java.nio.channels.ClosedChannelException: null
at io.netty.channel.AbstractChannel$AbstractUnsafe.ensureOpen(...)(Unknown Source) ~[waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]

[23:53:25 INFO]: [/73.25.22.81:53002] <-> InitialHandler has connected`

**Comment by Janmm14** [comment]
Did you report this to protocolsupport before?
Or does it only happen when you use waterfall and not bungeecord (both with same plugins)?

**Comment by electronicboy** [comment]
Feel free to reopen the issue if you can replicate without ProtocolSupport installed.
