### ISSUE TITLE
Proxy does not handle duplicate scoreboard teams across connections

### ISSUE THREAD

**Issue by 0z-zy** [PaperMC/Waterfall#318]
[23:25:54] [Netty Worker IO Thread #23/ERROR]: [/1.156.19.57:50127|Uber_Elite] <-> DownstreamBridge <-> [LegendBender] - encountered exception
java.lang.IllegalArgumentException: Team §7§0§l[§9§lP_Mc already exists in this scoreboard
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
	at net.md_5.bungee.api.score.Scoreboard.addTeam(Scoreboard.java:73) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:208) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
	at net.md_5.bungee.protocol.packet.Team.handle(Team.java:122) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:103) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:421) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:321) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:a4b5eaf:238]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

**Comment by 0z-zy** [comment]
What's even that?

**Comment by electronicboy** [comment]
> Team §7§0§l[§9§lP_Mc� already exists in this scoreboard

Known bungeecord issue, you can't swap to servers which duplicate scoreboard names, "fix" is to ensure that servers won't duplicate scoreboard team names, hopefully I'll try and take a proper stab at this sometime...

**Comment by Malachiel87** [comment]
any progress on this?

**Comment by Legendbender** [comment]
It's fixed for me after new updates

**Comment by Malachiel87** [comment]
i still see 
[17:51:04] [Netty Worker IO Thread #60/ERROR]: [/79.45.96.127:53816|Killator] <-> DownstreamBridge <-> [hub-1] - encountered exception
java.lang.IllegalArgumentException: Team 718eb already exists in this scoreboard
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c3d67e5:290]
	at net.md_5.bungee.api.score.Scoreboard.addTeam(Scoreboard.java:73) ~[waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c3d67e5:290]

**Comment by JHarris12345** [comment]
This issue is ongoing. Please fix

**Comment by Janmm14** [comment]
Workaround already presented in here.

**Comment by JHarris12345** [comment]
I dont understand the scoreboard fix or how I got about fixing it. I dont use default scoreboard

**Comment by Janmm14** [comment]
you need your plugins to use different scoreboard names on each server

**Comment by JHarris12345** [comment]
How do I do this @Janmm14. Also which plugins?

**Comment by electronicboy** [comment]
whichever plugin is creating the team that is conflicting on the other server, if you copied worlds over and aren't using plugins, potentially wanna consider delating the scoreboard.dat for the servers involved;

The only current fix is for bukkit plugins to take steps to prevent team name collisions across servers, this is an upstream issue

**Comment by Mystiflow** [comment]
One approach to fixing this is intercepting the Send Scoreboard packet, comparing the scoreboard names and if they match; just mutate the new name by 1 character or so (pretty sure a different name doesn't affect game mechanics) and then cancelling the original packet and sending the new one.

Any teams and objectives should then bind to the new scoreboard in theory.

**Comment by JHarris12345** [comment]
Hmm I use featherboard and TAB. Not sure how to go about fixing

**Comment by JHarris12345** [comment]
@electronicboy How do I prevent plugins from creating the same team names on my different servers?

**Comment by electronicboy** [comment]
Once again, you would need to speak to plug-in authors to try to mitigate
this;

**Comment by electronicboy** [comment]
If this is your suggested fix for the proxy, it would require additional
overheads to remap teams, would also create some potential oddball handling
if bungee plugins come into play

The ultimate fix is going to be to figure how to handle the server switch
better, my current thought is to just queue scoreboard packets and flush
them through, it is it's own set of headaches and mess, but the only other
alternative is to leave this solely on server/plug-in devs

**Comment by LuminousLoreBloom** [comment]
@electronicboy would intercepting the inbound Scoreboard Send work? Compare the previous scoreboard name with the latter and if they match; mutate the name by a character or so and send that packet instead? If I'm correct team/scoreboard packets don't require a scoreboard name they just latch on to the clients current scoreboard and if the client thinks it has a new scoreboard now; the team in theory won't pre exist? Would obviously need to confirm it wasn't the same server sending the Send Scoreboard packet though

**Comment by electronicboy** [comment]
The client only has a singular scoreboard, teams are shared across all instances; This issue is also not down to the client, this is pretty much 100% a flaw in bungees server connection process; The new target server sends it’s scoreboard data before the proxy has cleaned up the scoreboard on the client, rewriting team names just adds additional complexity, bloat and overheads in the proxy

as an afterthought, this would also break the clients tab completion for scoreboards in these cases

**Comment by LuminousLoreBloom** [comment]
I haven't looked into the client code but what purpose then does the name string serve in the Scoreboard Send packet?

> queue scoreboard packets and flush
them through

Do you mean storing each server sent scoreboard packet in a list and then sending the destroy packet for them on server switch?

**Comment by JH3Y50N** [comment]
I have a similar problem...

```
[02:17:01] [Netty Worker IO Thread #6/WARN]: [/000.00.00.000:6561|XXXXXXX] <-> DownstreamBridge <-> [Lobby] - A decoder exception has been thrown:
net.md_5.bungee.protocol.FastDecoderException: Error decoding packet class Team with contents:
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 3e 09 4c 6f 62 62 79 54 65 61 6d 00 09 4c 6f 62 |>.LobbyTeam..Lob|
|00000010| 62 79 54 65 61 6d 00 06 c2 a7 66 20 31 30 03 06 |byTeam....f 10..|
|00000020| 61 6c 77 61 79 73 ff 01 12 c2 a7 66 e2 97 8f 20 |always.....f... |
|00000030| 4c 6f 62 62 79 20 c2 a7 37 c2 bb                |Lobby ..7..     |
+--------+-------------------------------------------------+----------------+
Caused by: com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 5 path $
	at com.google.gson.JsonParser.parseReader(JsonParser.java:76) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at com.google.gson.JsonParser.parseString(JsonParser.java:51) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:90) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at net.md_5.bungee.protocol.DefinedPacket.readBaseComponent(DefinedPacket.java:93) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at net.md_5.bungee.protocol.packet.Team.read(Team.java:56) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at net.md_5.bungee.protocol.DefinedPacket.read(DefinedPacket.java:445) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:62) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:13) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_322]
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 5 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1659) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1465) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:551) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:433) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at com.google.gson.JsonParser.parseReader(JsonParser.java:71) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at com.google.gson.JsonParser.parseString(JsonParser.java:51) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:90) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at net.md_5.bungee.protocol.DefinedPacket.readBaseComponent(DefinedPacket.java:93) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at net.md_5.bungee.protocol.packet.Team.read(Team.java:56) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at net.md_5.bungee.protocol.DefinedPacket.read(DefinedPacket.java:445) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:62) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:13) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:333) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:454) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:472a702:551]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_322]
[02:17:01] [Netty Worker IO Thread #6/INFO]: [XXXXXXX] disconnected with: Conexão perdida com o servidor.
```

**Comment by Janmm14** [comment]
@JH3Y50N Your issue is completley different (unrelated to duplicate scores!) . FYI bungee has recently fixed a regression with <1.13 scoreboard/team stuff, so wait for waterfall to update.

**Comment by Malachiel87** [comment]
congraturations for reply a 2018 post
