### ISSUE TITLE
send fail

### ISSUE THREAD

**Issue by zhourui123** [PaperMC/Waterfall#326]
error happend when send 'Connect' netty message.
env:
waterfall 240
server mod :testSpongePlugin.jar ,testForgeMod.jar ,spongeforge-2768.jar
client mod: testForgeMod.jar
java 8+
forge version:  1.12.2-2768

water fall log
```
[16:34:18 INFO]: [zz8|/127.0.0.1:6528] <-> ServerConnector [lobby] has connected
[16:34:19 INFO]: [/127.0.0.1:6528|zz8] <-> DownstreamBridge <-> [mg_1] has disconnected
[16:55:53 INFO]: [zz8|/127.0.0.1:6528] <-> ServerConnector [mg_1] has connected
[16:55:53 INFO]: [zz6|/127.0.0.1:6343] <-> ServerConnector [mg_1] has connected
[16:55:55 INFO]: [zz8|/127.0.0.1:6528] <-> ServerConnector [mg_1] has disconnected
[16:55:55 INFO]: [/127.0.0.1:6343|zz6] <-> DownstreamBridge <-> [lobby] has disconnected
[16:56:32 INFO]: [zz6|/127.0.0.1:6343] <-> ServerConnector [lobby] has connected
[16:56:32 INFO]: [/127.0.0.1:6343|zz6] <-> DownstreamBridge <-> [mg_1] has disconnected
[16:58:25 INFO]: [zz8|/127.0.0.1:6528] <-> ServerConnector [mg_1] has connected
[16:58:25 INFO]: [zz6|/127.0.0.1:6343] <-> ServerConnector [mg_1] has connected
[16:58:26 INFO]: [zz8|/127.0.0.1:6528] <-> ServerConnector [mg_1] has disconnected
[16:58:27 INFO]: [/127.0.0.1:6343|zz6] <-> DownstreamBridge <-> [lobby] has disconnected
[16:59:03 INFO]: [zz6|/127.0.0.1:6343] <-> ServerConnector [lobby] has connected
[16:59:04 INFO]: [/127.0.0.1:6343|zz6] <-> DownstreamBridge <-> [mg_1] has disconnected
```

server log
```
> [16:58:26] [Netty Server IO #5/ERROR] [FML]: NetworkDispatcher exception
java.lang.NullPointerException: null
[16:58:26] [Netty Server IO #5/WARN] [io.netty.channel.AbstractChannelHandlerContext]: Failed to mark a promise as failure because it has succeeded already: DefaultChannelPromise@626c721e(success)
java.lang.NullPointerException: null
        at io.netty.util.internal.PromiseNotificationUtil.tryFailure(PromiseNotificationUtil.java:64) ~[PromiseNotificationUtil.class:?]
        at io.netty.channel.ChannelOutboundBuffer.safeFail(ChannelOutboundBuffer.java:674) ~[ChannelOutboundBuffer.class:?]
        at io.netty.channel.ChannelOutboundBuffer.remove0(ChannelOutboundBuffer.java:293) ~[ChannelOutboundBuffer.class:?]
        at io.netty.channel.ChannelOutboundBuffer.failFlushed(ChannelOutboundBuffer.java:616) ~[ChannelOutboundBuffer.class:?]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:667) ~[AbstractChannel$AbstractUnsafe.class:?]
        at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:607) ~[AbstractChannel$AbstractUnsafe.class:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.close(DefaultChannelPipeline.java:1276) ~[DefaultChannelPipeline$HeadContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:624) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:608) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.ChannelDuplexHandler.close(ChannelDuplexHandler.java:73) [ChannelDuplexHandler.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:624) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:608) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.ChannelOutboundHandlerAdapter.close(ChannelOutboundHandlerAdapter.java:71) [ChannelOutboundHandlerAdapter.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:624) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:608) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.ChannelOutboundHandlerAdapter.close(ChannelOutboundHandlerAdapter.java:71) [ChannelOutboundHandlerAdapter.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:624) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:608) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.ChannelOutboundHandlerAdapter.close(ChannelOutboundHandlerAdapter.java:71) [ChannelOutboundHandlerAdapter.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:624) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:608) [AbstractChannelHandlerContext.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.close(NetworkDispatcher.java:509) [NetworkDispatcher.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeClose(AbstractChannelHandlerContext.java:624) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:608) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.close(AbstractChannelHandlerContext.java:465) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.close(DefaultChannelPipeline.java:964) [DefaultChannelPipeline.class:?]
        at io.netty.channel.AbstractChannel.close(AbstractChannel.java:234) [AbstractChannel.class:?]
        at net.minecraft.network.NetworkManager.func_150718_a(NetworkManager.java:303) [gw.class:?]
        at net.minecraft.network.NetworkManager.exceptionCaught(NetworkManager.java:138) [gw.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131) [ChannelInboundHandlerAdapter.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.exceptionCaught(NetworkDispatcher.java:603) [NetworkDispatcher.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:87) [ChannelHandlerAdapter.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:87) [ChannelHandlerAdapter.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.ChannelHandlerAdapter.exceptionCaught(ChannelHandlerAdapter.java:87) [ChannelHandlerAdapter.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131) [ChannelInboundHandlerAdapter.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131) [ChannelInboundHandlerAdapter.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131) [ChannelInboundHandlerAdapter.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:131) [ChannelInboundHandlerAdapter.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:264) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:256) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.exceptionCaught(DefaultChannelPipeline.java:1301) [DefaultChannelPipeline$HeadContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.notifyHandlerException(AbstractChannelHandlerContext.java:850) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:778) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.ChannelDuplexHandler.flush(ChannelDuplexHandler.java:117) [ChannelDuplexHandler.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) [ChannelOutboundHandlerAdapter.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) [ChannelOutboundHandlerAdapter.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.ChannelOutboundHandlerAdapter.flush(ChannelOutboundHandlerAdapter.java:115) [ChannelOutboundHandlerAdapter.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush(AbstractChannelHandlerContext.java:768) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.flush(AbstractChannelHandlerContext.java:749) [AbstractChannelHandlerContext.class:?]
        at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.flush(NetworkDispatcher.java:555) [NetworkDispatcher.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:802) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) [AbstractChannelHandlerContext.class:?]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) [DefaultChannelPipeline.class:?]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) [AbstractChannel.class:?]
        at net.minecraft.network.NetworkManager$4.run(NetworkManager.java:245) [gw$4.class:?]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [AbstractEventExecutor.class:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) [SingleThreadEventExecutor.class:?]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442) [NioEventLoop.class:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [SingleThreadEventExecutor$5.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
```

**Comment by electronicboy** [comment]
We need proper reproduction steps, all I can see here is that something on forge appears to be trying to double process something

**Comment by zhourui123** [comment]
It looks as if it happened by accident, I want to know how do you see that it's double process?  : )

**Comment by electronicboy** [comment]
`Failed to mark a promise as failure because it has succeeded already: DefaultChannelPromise@626c721e(success)`

**Comment by zhourui123** [comment]
I don't know how to trigger it again, Sorry to bother you, I will further confirm the problem and submit it.
