### ISSUE TITLE
Empty Packet! error

### ISSUE THREAD

**Issue by andris155** [PaperMC/Waterfall#338]
```
[12:26:35] [Netty Worker IO Thread #2/ERROR]: [/xx.xxx.xx.xx:54479|Shockwave] <-> DownstreamBridge <-> [survival] - encountered exception
io.netty.handler.codec.CorruptedFrameException: Empty Packet!
	at net.md_5.bungee.protocol.Varint21FrameDecoder.decode(Varint21FrameDecoder.java:43) ~[Waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9abc717:241]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) ~[Waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9abc717:241]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[Waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9abc717:241]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[Waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9abc717:241]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9abc717:241]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9abc717:241]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9abc717:241]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[Waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9abc717:241]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9abc717:241]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9abc717:241]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9abc717:241]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[Waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9abc717:241]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9abc717:241]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9abc717:241]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[Waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9abc717:241]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799) ~[Waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9abc717:241]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:433) ~[Waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9abc717:241]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:330) ~[Waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9abc717:241]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) ~[Waterfall-A.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:9abc717:241]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by electronicboy** [comment]
As the error states, Something sent an empty packet, The fix is to stop your server from doing that.
