### ISSUE TITLE
Getting this error in my WaterFall console.

### ISSUE THREAD

**Issue by M4RC0Sx** [PaperMC/Waterfall#351]
[16:30:06] [Netty Worker IO Thread #12/ERROR]: [/213.251.182.111:44498] <-> InitialHandler - encountered exception
io.netty.handler.codec.DecoderException: Error decoding packet class Handshake with contents:
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 00 04 09 35 2e 39 2e 37 37                      |...5.9.77       |
+--------+-------------------------------------------------+----------------+
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:68) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:12) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
	at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:249) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:433) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:330) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(3) + length(9) exceeds writerIndex(9): PooledSlicedByteBuf(ridx: 3, widx: 9, cap: 9/9, unwrapped: PooledUnsafeDirectByteBuf(ridx: 10, widx: 16, cap: 16))
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1437) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1420) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:895) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:903) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
	at net.md_5.bungee.protocol.DefinedPacket.readString(DefinedPacket.java:36) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
	at net.md_5.bungee.protocol.packet.Handshake.read(Handshake.java:27) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
	at net.md_5.bungee.protocol.DefinedPacket.read(DefinedPacket.java:206) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:46) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
	... 32 more

**Comment by colo13verdadeo** [comment]
I have the same error :(

**Comment by electronicboy** [comment]
Your server sent a malformed packet, this is often down to plugins on the server manipulating network data improperly
