### ISSUE TITLE
Waterfall error console

### ISSUE THREAD

**Issue by colo13verdadeo** [PaperMC/Waterfall#352]
21:32:04 ERROR]: [/190.48.75.221:55518|NaiGuin] <-> DownstreamBridge <-> [survival] - encountered exception
io.netty.handler.codec.DecoderException: Error decoding packet unknown with contents:

at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:68) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:12) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:799) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:433) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:330) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(0) + length(1) exceeds writerIndex(0): AbstractPooledDerivedByteBuf$PooledNonRetainedSlicedByteBuf(ridx: 0, widx: 0, cap: 0/0, unwrapped: PooledUnsafeDirectByteBuf(ridx: 2, widx: 2, cap: 448))
at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1437) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:121) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:111) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:39) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:08b4e88:253]
... 27 more

**Comment by electronicboy** [comment]
Your server sent an empty packet, this is often down to plugins installed on the server manipulating data improperly
