### ISSUE TITLE
Handshake attack

### ISSUE THREAD

**Issue by xBlackInkk** [PaperMC/Waterfall#380]
Hello,
Some person is attacking me by handshake packet.
Here is the console log:

```
[14:39:34] [Netty Worker IO Thread #1/ERROR]: [/102.164.248.51:45907] <-> InitialHandler - encountered exception
io.netty.handler.codec.DecoderException: Error decoding packet class Handshake with contents:
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 00                                              |.               |
+--------+-------------------------------------------------+----------------+
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:82) ~[waterfall-282.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:b438f80:282]
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:12) ~[waterfall-282.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:b438f80:282]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[waterfall-282.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:b438f80:282]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[waterfall-282.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:b438f80:282]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[waterfall-282.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:b438f80:282]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[waterfall-282.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:b438f80:282]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[waterfall-282.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:b438f80:282]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[waterfall-282.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:b438f80:282]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426) ~[waterfall-282.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:b438f80:282]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[waterfall-282.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:b438f80:282]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[waterfall-282.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:b438f80:282]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[waterfall-282.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:b438f80:282]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[waterfall-282.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:b438f80:282]
	at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:249) ~[waterfall-282.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:b438f80:282]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) ~[waterfall-282.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:b438f80:282]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[waterfall-282.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:b438f80:282]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[waterfall-282.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:b438f80:282]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[waterfall-282.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:b438f80:282]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[waterfall-282.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:b438f80:282]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[waterfall-282.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:b438f80:282]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall-282.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:b438f80:282]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[waterfall-282.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:b438f80:282]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[waterfall-282.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:b438f80:282]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[waterfall-282.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:b438f80:282]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) ~[waterfall-282.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:b438f80:282]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[waterfall-282.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:b438f80:282]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[waterfall-282.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:b438f80:282]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) ~[waterfall-282.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:b438f80:282]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:796) ~[waterfall-282.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:b438f80:282]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:427) ~[waterfall-282.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:b438f80:282]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:328) ~[waterfall-282.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:b438f80:282]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[waterfall-282.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:b438f80:282]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): PooledSlicedByteBuf(ridx: 1, widx: 1, cap: 1/1, unwrapped: PooledUnsafeDirectByteBuf(ridx: 2, widx: 3, cap: 3))
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1428) ~[waterfall-282.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:b438f80:282]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:723) ~[waterfall-282.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:b438f80:282]
	at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:148) ~[waterfall-282.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:b438f80:282]
	at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:138) ~[waterfall-282.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:b438f80:282]
	at net.md_5.bungee.protocol.packet.Handshake.read(Handshake.java:26) ~[waterfall-282.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:b438f80:282]
	at net.md_5.bungee.protocol.DefinedPacket.read(DefinedPacket.java:233) ~[waterfall-282.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:b438f80:282]
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:60) ~[waterfall-282.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:b438f80:282]
	... 32 more
```
Please fix it fast if you can,
thank you in advance!

**Comment by electronicboy** [comment]
There is nothing here for us to fix, The proxy is doing its main job: Proxying, people sending bad traffic to the proxy doesn't change its job. If people are persistently sending such traffic, I'd suggest using your firewall to try to prevent it

**Comment by xBlackInkk** [comment]
Thank you for your response.
I used firewall and it works :)

**Comment by Janmm14** [comment]
Bungee recently (weeks or 1-2 months ago) changed the connection throttle to prevent dos handshake attacks. I don't think there can be done much more useful without adding a layer7 (d)dos detector into bungee.
