### ISSUE TITLE
Error in console Empty packet

### ISSUE THREAD

**Issue by Xofters** [PaperMC/Waterfall#398]
```
[19:51:04 ERROR]: [/188.69.209.5:52564|vegetafan] <-> DownstreamBridge <-> [s2] - encountered exception
io.netty.handler.codec.CorruptedFrameException: Empty Packet!
at net.md_5.bungee.protocol.Varint21FrameDecoder.decode(Varint21FrameDecoder.java:44) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:796) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:427) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:328) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[19:51:04 INFO]: [Belarus82] disconnected with: The server you were previously on went down, you have been connected to a fallback server
[19:51:04 INFO]: [vegetafan] disconnected with: The server you were previously on went down, you have been connected to a fallback server
[19:51:04 INFO]: [/78.62.226.161:38116|TheMinePlayeris] <-> DownstreamBridge <-> [s2] has disconnected
[19:51:04 INFO]: [/89.116.185.209:64343|Belarus82] <-> DownstreamBridge <-> [s2] has disconnected
[19:51:04 INFO]: [/188.69.209.5:52564|vegetafan] <-> DownstreamBridge <-> [s2] has disconnected
[19:51:04 ERROR]: [/89.116.7.93:27748|G3rkka] <-> DownstreamBridge <-> [s2] - encountered exception
io.netty.handler.codec.CorruptedFrameException: Empty Packet!
at net.md_5.bungee.protocol.Varint21FrameDecoder.decode(Varint21FrameDecoder.java:44) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:796) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:427) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:328) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
[19:51:04 INFO]: [G3rkka] disconnected with: The server you were previously on went down, you have been connected to a fallback server
[19:51:04 INFO]: [/89.116.7.93:27748|G3rkka] <-> DownstreamBridge <-> [s2] has disconnected
[19:51:04 ERROR]: [/78.56.133.237:54238|Skyorie] <-> DownstreamBridge <-> [s2] - encountered exception
io.netty.handler.codec.CorruptedFrameException: Empty Packet!
```

**Comment by electronicboy** [comment]
Something on your server caused an empty packet to be sent to the proxy, by default bungee considers this an error, whereas the client will generally just ignore it. There is an option in waterfall.yml to allow such broken state, however you should generally look into finding what is causing it and removing it.
