### ISSUE TITLE
Error whilst handling query packet from /195.201.249.154:60159

### ISSUE THREAD

**Issue by TomLewis** [PaperMC/Waterfall#399]
I get this a lot in my logs, and its all the same IP.
edit: found out its a game tracking website: https://www.game-state.com/198.100.146.34:25565/

```
[10:58:03] [Netty Worker IO Thread #0/WARN]: Error whilst handling query packet from /195.201.249.154:60159
java.lang.IllegalStateException: No session!
	at net.md_5.bungee.query.QueryHandler.handleMessage(QueryHandler.java:99) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
	at net.md_5.bungee.query.QueryHandler.channelRead0(QueryHandler.java:60) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
	at net.md_5.bungee.query.QueryHandler.channelRead0(QueryHandler.java:26) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
	at io.netty.channel.epoll.EpollDatagramChannel$EpollDatagramChannelUnsafe.epollInReady(EpollDatagramChannel.java:513) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:427) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:328) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:1f16030:286]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

**Comment by electronicboy** [comment]
There isn't much we can do about invalid traffic being sent to the proxy, we could probably remove the trace itself like other exceptions in this area, but overall, the proxy is working as intended
