### ISSUE TITLE
Waterfall Crash [java.lang.RuntimeException: VarInt too big]

### ISSUE THREAD

**Issue by AutoComplete1** [PaperMC/Waterfall#401]
Hello,
currently our bungeecord is crashed after my research with the help of wrong packets. The crash is so that the proxy is not reachable for about one minute and is then reachable again. Here's the exception: 
```
io.netty.handler.codec.DecoderException: java.lang.RuntimeException: VarInt too big
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:98) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:249) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:249) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerRemoved(AbstractChannelHandlerContext.java:961) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:638) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:481) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:421) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.handler.codec.haproxy.HAProxyMessageDecoder.channelRead(HAProxyMessageDecoder.java:225) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:249) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:796) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:427) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:328) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: java.lang.RuntimeException: VarInt too big
	at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:154) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:138) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:53) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:12) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[bungee.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c0c84ca:287]
	... 46 more```

**Comment by xxDark** [comment]
It is not related to the proxy itself, someone is sending invalid packets

**Comment by AutoComplete1** [comment]
@xxDark I am aware of this, but I have a problem with the fact that the proxy is not reachable for about one minute and all players are getting kicked. If only the error in the console would come, I wouldn't have a problem with it.
