### ISSUE TITLE
terminal console error 1.14.4

### ISSUE THREAD

**Issue by successed** [PaperMC/Waterfall#407]
[10:30:21 ERROR]: Exception in thread "main" java.lang.NoClassDefFoundError: org/jline/terminal/Terminal$MouseTracking
[10:30:21 ERROR]:         at org.jline.reader.impl.LineReaderImpl.doCleanup(LineReaderImpl.java:2345)
[10:30:21 ERROR]:         at org.jline.reader.impl.LineReaderImpl.cleanup(LineReaderImpl.java:2332)
[10:30:21 ERROR]:         at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:626)
[10:30:21 ERROR]:         at org.jline.reader.impl.LineReaderImpl.readLine(LineReaderImpl.java:404)
[10:30:21 ERROR]:         at net.minecrell.terminalconsole.SimpleTerminalConsole.readCommands(SimpleTerminalConsole.java:157)
[10:30:21 ERROR]:         at net.minecrell.terminalconsole.SimpleTerminalConsole.start(SimpleTerminalConsole.java:140)
[10:30:21 ERROR]:         at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
[10:30:21 ERROR]:         at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
[10:30:21 ERROR]: Caused by: java.lang.ClassNotFoundException: org.jline.terminal.Terminal$MouseTracking
[10:30:21 ERROR]:         at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[10:30:21 ERROR]:         at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[10:30:21 ERROR]:         at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
[10:30:21 ERROR]:         at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[10:30:21 ERROR]:         ... 8 more

**Comment by stephan-gh** [comment]
Related: https://github.com/PaperMC/Paper/issues/894#issuecomment-331787892

**Comment by successed** [comment]
> Related: [PaperMC/Paper#894 (comment)](https://github.com/PaperMC/Paper/issues/894#issuecomment-331787892)

My problem is waterfall, and you tag is paper problem mean,  i not have paper problem.

**Comment by electronicboy** [comment]
The issue is generally the exact same cause, can you reproduce this issue?
