### ISSUE TITLE
Forestry 【Minecart with Apiary】  Place  Player dropped

### ISSUE THREAD

**Issue by Songxwn** [PaperMC/Waterfall#410]
kpmyon] <-> DownstreamBridge <-> [shengcun] - encountered exception
java.lang.IllegalArgumentException: Unknown meta type 14: Using mods? refer to disable_entity_metadata_rewrite in waterfall.yml
        at net.md_5.bungee.entitymap.EntityMap.rewriteMetaVarInt(EntityMap.java:283) ~[waterfall-289.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at net.md_5.bungee.entitymap.EntityMap.rewriteMetaVarInt(EntityMap.java:135) ~[waterfall-289.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at net.md_5.bungee.entitymap.EntityMap_1_12_1.rewriteClientbound(EntityMap_1_12_1.java:151) ~[waterfall-289.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at net.md_5.bungee.entitymap.EntityMap.rewriteClientbound(EntityMap.java:101) ~[waterfall-289.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:139) ~[waterfall-289.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:112) ~[waterfall-289.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[waterfall-289.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[waterfall-289.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[waterfall-289.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[waterfall-289.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[waterfall-289.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[waterfall-289.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[waterfall-289.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[waterfall-289.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[waterfall-289.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426) ~[waterfall-289.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[waterfall-289.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[waterfall-289.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[waterfall-289.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[waterfall-289.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall-289.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[waterfall-289.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[waterfall-289.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[waterfall-289.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) ~[waterfall-289.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[waterfall-289.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[waterfall-289.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) ~[waterfall-289.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[waterfall-289.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677) ~[waterfall-289.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612) ~[waterfall-289.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529) ~[waterfall-289.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491) ~[waterfall-289.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[waterfall-289.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:eb6cf93:289]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
[18:24:23 INFO]: [kpmyon] disconnected with: The server you were previously on went down, you have been connected to a fallback server

**Comment by electronicboy** [comment]
`java.lang.IllegalArgumentException: Unknown meta type 14: Using mods? refer to disable_entity_metadata_rewrite in waterfall.yml` disable entity metadata rewriting

**Comment by Songxwn** [comment]
Sorry to bother, I didn't look carefully.
