### ISSUE TITLE
Error decoding packet

### ISSUE THREAD

**Issue by Hite29** [PaperMC/Waterfall#442]
Hi, can u help me? I have this error. 

[20:36:30] [Netty Worker IO Thread #15/ERROR]: [/188.75.186.162:50102] <-> InitialHandler - encountered exception
io.netty.handler.codec.DecoderException: Error decoding packet class Handshake with contents:
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 00                                              |.               |
+--------+-------------------------------------------------+----------------+
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:74) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:12) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:426) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:796) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:427) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:328) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(1) + length(1) exceeds writerIndex(1): PooledSlicedByteBuf(ridx: 1, widx: 1, cap: 1/1, unwrapped: PooledUnsafeDirectByteBuf(ridx: 2, widx: 1000, cap: 1024))
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1428) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:723) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:148) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at net.md_5.bungee.protocol.DefinedPacket.readVarInt(DefinedPacket.java:138) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at net.md_5.bungee.protocol.packet.Handshake.read(Handshake.java:26) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at net.md_5.bungee.protocol.DefinedPacket.read(DefinedPacket.java:233) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:52) ~[server.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:c354548:295]
	... 25 more

**Comment by electronicboy** [comment]
Something sent a bad packet
