### ISSUE TITLE
Timer already cancelled

### ISSUE THREAD

**Issue by Yboy06** [PaperMC/Waterfall#462]
Hello:
I am getting this error when I load my WaterFall server.

```
[21:41:22 ERROR]: Exception in thread "main" java.lang.IllegalStateException: Timer already cancelled.
[21:41:22 ERROR]:       at java.util.Timer.sched(Timer.java:397)
[21:41:22 ERROR]:       at java.util.Timer.scheduleAtFixedRate(Timer.java:328)
[21:41:22 ERROR]:       at net.md_5.bungee.BungeeCord.start(BungeeCord.java:290)
[21:41:22 ERROR]:       at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
[21:41:22 ERROR]:       at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
```

I hope someone can help me

**Comment by electronicboy** [comment]
The only time that timer is stopped is when the proxy is shutting down, more than likely down to plugins, etc
