### ISSUE TITLE
Shorten / Speedup "Cannot request protocol" exception

### ISSUE THREAD

**Issue by Sneakometer** [PaperMC/Waterfall#469]
As the "corrupted frame" and bad "packet id" exceptions were shortened to one line, i wonder if it is possible to do the same thing for "Cannot request protocol" exceptions because hey can be used to spam the console and lag the server.

Sample exception:
`[21:04:52 ERROR]: [/192.254.99.49:35795] <-> InitialHandler - encountered exception
java.lang.IllegalArgumentException: Cannot request protocol 49
        at net.md_5.bungee.connection.InitialHandler.handle(InitialHandler.java:354) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at net.md_5.bungee.protocol.packet.Handshake.handle(Handshake.java:44) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:105) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at io.netty.handler.codec.ByteToMessageDecoder.handlerRemoved(ByteToMessageDecoder.java:253) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:437) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:87d2873:326]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]`

It could be shortened to just:
`InitialHandler - cannot request protocol 49`
like e.g. the already shortened
`InitialHandler - corrupted frame: length wider than 21-bit`
or
`InitialHandler - bad packet ID, are mods in use!? No more bytes reading varint`

Thanks!

**Comment by MrIvanPlays** [comment]
https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/connection/InitialHandler.java#L347

Basically exception shouldn't be thrown, the client should be dropped without exception.

**Comment by electronicboy** [comment]
Already resolved by upstream
