### ISSUE TITLE
issue with dns resolving

### ISSUE THREAD

**Issue by PhanaticD** [PaperMC/Waterfall#481]
so today mojang session servers been shit, and I assume they updated them a bit ago because the IP changed. However bungee is not updating the resolved IP, as you can see it is different when I use the "host" command, vs what it shows in console for players unable to join

greload does fix it, also probably relevant I do have use netty dns enabled

```
> host sessionserver.mojang.com
sessionserver.mojang.com has address 99.84.223.181
```

```
[17:08:13 ERROR]: Error authenticating A21 with minecraft.net
io.netty.channel.ConnectTimeoutException: connection timed out: sessionserver.mojang.com/99.84.109.106:443
        at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe$2.run(AbstractEpollChannel.java:575) ~[bungee.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:3b79a30:135]
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[bungee.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:3b79a30:135]
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170) ~[bungee.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:3b79a30:135]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[bungee.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:3b79a30:135]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[bungee.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:3b79a30:135]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) ~[bungee.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:3b79a30:135]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[bungee.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:3b79a30:135]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[bungee.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:3b79a30:135]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_231]
```

**Comment by TNTUP** [comment]
Unrelated, thats why my console client/magic launcher throwing me invalid session. Darnit Mojang, they always screw up things :/

**Comment by Chew** [comment]
#550 added a way to customize the session server. Utilize this if you are still experiencing this issue.

**Comment by PhanaticD** [comment]
This issue has nothing to do with customizing the session server did you even read it

**Comment by Chew** [comment]
The error was with it not being able to access it. So if it can't resolve, you can change it to something else that does. Anyway, is this still an issue?

**Comment by PhanaticD** [comment]
no, the issue is that it resolved the WRONG IP

it is still an issue, but it is rare, as it only happens when mojang changes their session servers up which only happens once every few months

**Comment by Chew** [comment]
Yeah, it's mostly a DNS caching error then, what do you propose the fix to be?

**Comment by PhanaticD** [comment]
well what I did was disable the netty resolver and added -Dnetworkaddress.cache.ttl=10 to startup arguments

but that solution does not work with netty resolver enabled
