### ISSUE TITLE
Authentification error

### ISSUE THREAD

**Issue by AlexProgrammerDE** [PaperMC/Waterfall#486]
I don't now if this is something to worry about. Maybe is this something on Mojangs side. It was able to log in after the third time.
Here is my log:
```
[13:14:06 ERROR]: Error authenticating Pistonmaster with minecraft.net
io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'sessionserver.mojang.com' failed to resolve 'sessionserver.mojang.com' after 2 queries
        at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:925) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
        at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:884) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
        at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:356) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
        at io.netty.resolver.dns.DnsResolveContext.access$600(DnsResolveContext.java:64) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
        at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:405) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
        at io.netty.resolver.dns.DnsQueryContext.tryFailure(DnsQueryContext.java:225) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
        at io.netty.resolver.dns.DnsQueryContext$4.run(DnsQueryContext.java:177) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:b02f64c:327]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: io.netty.resolver.dns.DnsNameResolverTimeoutException: [/192.168.178.1:53] query via UDP timed out after 5000 milliseconds (no stack trace available)
```

**Comment by electronicboy** [comment]
Your DNS server timed out

**Comment by AlexProgrammerDE** [comment]
@electronicboy is there anything i can do to prevent this?

**Comment by electronicboy** [comment]
You'd need to work out why it timed out, you could disable nettys DNS resolver in waterfall.yml to rely on java/the OSes stack, might offer better caching or something if this occurs often

**Comment by AlexProgrammerDE** [comment]
@electronicboy thanks. I will try this if it occurs multiple times. 👍
