### ISSUE TITLE
Waterfall kicks everyone

### ISSUE THREAD

**Issue by hurrgurl** [PaperMC/Waterfall#493]
What's happening there?

```
EncoderException : java.lang.NullPointerException @ io.netty.handler.codec.MessageToByteEncoder:125
io.netty.handler.codec.EncoderException: java.lang.NullPointerException
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:e45fb1f:340]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:e45fb1f:340]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:e45fb1f:340]
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:e45fb1f:340]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:e45fb1f:340]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:e45fb1f:340]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:e45fb1f:340]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:e45fb1f:340]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:e45fb1f:340]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.NullPointerException
```

**Comment by Janmm14** [comment]
Please search your log for a full stack trace. This one is not complete, it is missing "at" lines after "Caused by". Stack trace shortening happens when an exception is thorwn thousands of times to improve performance.

**Comment by hurrgurl** [comment]
```
io.netty.handler.codec.EncoderException: java.lang.NullPointerException
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:e45fb1f:340]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:e45fb1f:340]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:e45fb1f:340]
	at io.netty.channel.AbstractChannelHandlerContext$WriteTask.run(AbstractChannelHandlerContext.java:1071) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:e45fb1f:340]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:e45fb1f:340]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:e45fb1f:340]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:e45fb1f:340]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:e45fb1f:340]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:e45fb1f:340]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.lang.NullPointerException
	at net.md_5.bungee.protocol.DefinedPacket.writeString(DefinedPacket.java:16) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:e45fb1f:340]
	at net.md_5.bungee.protocol.packet.PlayerListItem.write(PlayerListItem.java:90) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:e45fb1f:340]
	at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:24) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:e45fb1f:340]
	at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:9) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:e45fb1f:340]
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:e45fb1f:340]
	... 9 more
```

**Comment by electronicboy** [comment]
something on your proxy tried to send a mangled set of properties in the player list packet
