### ISSUE TITLE
Can't Type Command (Bug)

### ISSUE THREAD

**Issue by Kale-Ko** [PaperMC/Waterfall#507]
Every time I type a space after a proper command I get kicked for: 
Method became inaccessible: TabCompleteEvent(super=TargetedEvent(sender=OrangeKale64, receiver=net.md_5.bungee.ServerConnection@451d461e), cancelled=false, cursor=/login , suggestions=[]) @ net.md_5.bungee.event.EventBus:50
As you can see I was trying to login to my server, but I get kicked every time I type the space after and proper command or if I send anything to chat. Some help please.

java.lang.Error: Method became inaccessible: TabCompleteEvent(super=TargetedEvent(sender=OrangeKale64, receiver=net.md_5.bungee.ServerConnection@451d461e), cancelled=false, cursor=/login , suggestions=[])
        at net.md_5.bungee.event.EventBus.post(EventBus.java:50) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:453) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
        at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:185) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
        at net.md_5.bungee.protocol.packet.TabCompleteRequest.handle(TabCompleteRequest.java:87) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:105) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
Caused by: java.lang.IllegalAccessException: Class net.md_5.bungee.event.EventHandlerMethod can not access a member of class com.vk2gpz.commanddoesnotexistbc.a with modifiers "public"
        at sun.reflect.Reflection.ensureMemberAccess(Unknown Source) ~[?:1.8.0_251]
        at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(Unknown Source) ~[?:1.8.0_251]
        at java.lang.reflect.AccessibleObject.checkAccess(Unknown Source) ~[?:1.8.0_251]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:47) ~[Waterfall.jar:git:Waterfall-Bootstrap:1.15-SNAPSHOT:983fe27:344]
        ... 36 more
[14:13:40 INFO]: [OrangeKale64] disconnected with: Error : Method became inaccessible: TabCompleteEvent(super=TargetedEvent(sender=OrangeKale64, receiver=net.md_5.bungee.ServerConnection@451d461e), cancelled=false, cursor=/login , suggestions=[]) @ net.md_5.bungee.event.EventBus:50
[14:13:40 INFO]: [/172.19.99.236:61638|OrangeKale64] -> UpstreamBridge has disconnected
[14:13:40 INFO]: [/172.19.99.236:61638|OrangeKale64] <-> DownstreamBridge <-> [hub] has disconnected

**Comment by electronicboy** [comment]
`Caused by: java.lang.IllegalAccessException: Class net.md_5.bungee.event.EventHandlerMethod can not access a member of class com.vk2gpz.commanddoesnotexistbc.a with modifiers "public"`
Speak to the plugin author
