### ISSUE TITLE
NPE and io.netty errors

### ISSUE THREAD

**Issue by ren-kun** [PaperMC/Waterfall#518]
Im using:

Forge 2838
spongeforge 2838 for 1.12.2
Waterfall #346

And i receive two different, separate errors when connecting in. The first from the lobby:

Ren_kun lost connection: Internal Exception: io.netty.channel.unix.Errors$NativeIoException: syscall:read(..) failed: Connection reset by peer

and the client gets:

Internal Exception: java.lang.NullPointerException

while waterfall receives:

[|/45.127.94.8:60757]: <-> ServerConnector [lobby] has connected
[/45.127.94.8:60757|Ren_kun]: -> UpstreamBridge has disconnected
[/45.127.94.8:60757|Ren_kun]: <-> DownstreamBridge <-> [lobby] has disconnected

I have tried to:
- Relog from my account

**Comment by electronicboy** [comment]
need the full error from the client, waterfalls error is just saying that the client closed the connection improperly

**Comment by ren-kun** [comment]
I think this is the log you want.
https://paste.ee/p/wOZp0

**Comment by electronicboy** [comment]
```
[20:22:15] [Netty Client IO #0/INFO] [net.minecraft.advancements.AdvancementList]: Loaded 577 advancements
[20:22:15] [Netty Client IO #0/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.network.FMLNetworkEvent$ClientConnectedToServerEvent@24f327f:
java.lang.IllegalStateException: null
	at com.google.common.base.Preconditions.checkState(Preconditions.java:429) ~[guava-21.0.jar:?]
	at net.minecraft.advancements.Advancement.getTree(SourceFile:565) ~[i.class:?]
	at net.minecraft.advancements.AdvancementTreeNode.handler$zba000$onLayout(SourceFile:546) ~[t.class:?]
	at net.minecraft.advancements.AdvancementTreeNode.func_192323_a(SourceFile:224) ~[t.class:?]
	at net.minecraft.advancements.AdvancementManager.func_192779_a(AdvancementManager.java:76) ~[ns.class:?]
	at net.minecraft.advancements.AdvancementManager.<init>(AdvancementManager.java:60) ~[ns.class:?]
	at codersafterdark.reskillable.client.base.ClientProxy.connect(ClientProxy.java:42) ~[ClientProxy.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1445_ClientProxy_connect_ClientConnectedToServerEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.forgeBridge$post(EventBus.java:753) [EventBus.class:?]
```
This is an issue with whatever is going on here, would suggest that something threw in an invalid advancement data somewhere
