### ISSUE TITLE
Invalid plugin.yml

### ISSUE THREAD

**Issue by TheDeafCreeper** [PaperMC/Waterfall#525]
I have tested builds 358, 357, and 356 all downloaded from https://papermc.io/downloads#Waterfall and they all fail to start with the error:
`>.... [23:23:21 ERROR]: Could not load 'plugins/Waterfall.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:162) ~[patched_1.16.1.jar:git-Paper-1]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:148) ~[patched_1.16.1.jar:git-Paper-1]
at org.bukkit.craftbukkit.v1_16_R1.CraftServer.loadPlugins(CraftServer.java:386) ~[patched_1.16.1.jar:git-Paper-1]
at net.minecraft.server.v1_16_R1.DedicatedServer.init(DedicatedServer.java:208) ~[patched_1.16.1.jar:git-Paper-1]
at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:940) ~[patched_1.16.1.jar:git-Paper-1]
at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.1.jar:git-Paper-1]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
... 7 more`

Server Version: git-Paper-27 (MC: 1.16.1)

**Comment by nadecancode** [comment]
LOL

**Comment by LuminousLoreBloom** [comment]
You need to put the Waterfall.jar in the folder before plugins, then make sure you remove it from the plugins folder.

**Comment by TheDeafCreeper** [comment]
Ah, its a server jar not plugin; Got it.
First time using Bungee/Waterfall, lol
