### ISSUE TITLE
Server kick when bungeecord send a chat message

### ISSUE THREAD

**Issue by JH3Y50N** [PaperMC/Waterfall#526]
```
[15:03:58 ERROR]: [Samukage|/189.63.128.200:60378] <-> ServerConnector [RankUP_OP] - exception processing exception
java.lang.NullPointerException: null
        at net.md_5.bungee.util.ChatComponentTransformer.legacyHoverTransform(ChatComponentTransformer.java:44) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:d0f82f3:359]
        at net.md_5.bungee.util.ChatComponentTransformer.transform(ChatComponentTransformer.java:111) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:d0f82f3:359]
        at net.md_5.bungee.UserConnection.sendMessage(UserConnection.java:475) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:d0f82f3:359]
        at net.md_5.bungee.UserConnection.sendMessage(UserConnection.java:457) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:d0f82f3:359]
        at net.md_5.bungee.UserConnection.sendMessage(UserConnection.java:442) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:d0f82f3:359]
        at net.md_5.bungee.ServerConnector.exception(ServerConnector.java:91) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:d0f82f3:359]
        at net.md_5.bungee.netty.HandlerBoss.exceptionCaught(HandlerBoss.java:177) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:d0f82f3:359]
        at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:d0f82f3:359]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:381) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:d0f82f3:359]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:d0f82f3:359]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:d0f82f3:359]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:d0f82f3:359]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:d0f82f3:359]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:d0f82f3:359]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:d0f82f3:359]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:d0f82f3:359]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:d0f82f3:359]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:d0f82f3:359]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:d0f82f3:359]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:d0f82f3:359]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:d0f82f3:359]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:d0f82f3:359]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:d0f82f3:359]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:d0f82f3:359]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:d0f82f3:359]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:d0f82f3:359]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:d0f82f3:359]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:d0f82f3:359]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:d0f82f3:359]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:d0f82f3:359]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:d0f82f3:359]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:d0f82f3:359]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:d0f82f3:359]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

```

**Comment by xAsbeel** [comment]
Everything works fine on client version 1.16.1. 
I think any version below is broken, on 1.15.2 client cannot switch server, also cannot send bungee command.

**Comment by haeiven** [comment]
i'm having the same issue in 1.8.9

https://paste.soleria.eu/ovukonekac.md
