### ISSUE TITLE
disconnected with: IllegalStateException : Adding 1 elements would exceed capacity of 128 @ com.google.common.base.Preconditions:593

### ISSUE THREAD

**Issue by dementisimus** [PaperMC/Waterfall#545]
comment: only one player gets kicked. Other players remain on the server.

`
java.lang.IllegalStateException: Adding 1 elements would exceed capacity of 128
	at com.google.common.base.Preconditions.checkState(Preconditions.java:593) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at net.md_5.bungee.util.BoundedArrayList.checkSize(BoundedArrayList.java:19) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at net.md_5.bungee.util.BoundedArrayList.add(BoundedArrayList.java:25) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:269) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at net.md_5.bungee.protocol.packet.PluginMessage.handle(PluginMessage.java:102) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:105) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.2-SNAPSHOT:9234e50:358]
	at java.lang.Thread.run(Thread.java:832) [?:?]
`

**Comment by Janmm14** [comment]
Very likely malicious player.

**Comment by Brokkonaut** [comment]
No it is some bug in here:
https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/connection/UpstreamBridge.java#L251
All (not cancelled) minecraft:register or minecraft:brand messages from the client to the bungee since the client connected are stored in a list and sent to the new server after a server switch.

The problem is that those messages are never removed from that list and after every server switch the client resends the minecraft:register and minecraft:brand packets. So they stack up and at some time will reach the limit of 128 and kick the player. We can see this very often since 1.16 on our server, i got kicked some times too.

I would recommend not to store them in that list at all (at least for 1.16 clients), because the client will resend them anyways. so there is no need to store them (maybe it was different in a previous version, i did not test that)

**Comment by Leymooo** [comment]
Client only resends `minecraft:brand` or `MC|Brand` when recieves Login(JoinGame) packet. Maybe forge or fabric resend register stuff but not vanilla

**Comment by Brokkonaut** [comment]
I created a plugin that logs those messages for debugging. The vanilla client definitely sends a minecraft:brand on server switch. Forge/Fabric clients also send one or more minecraft:register packets on server switch.

Vanilla Client:

[playername|/x.x.x.x:50282] <-> ServerConnector [Farmen] has connected
Setting stored Location for playername: Farmen
[/x.x.x.x:50282|playername] <-> DownstreamBridge <-> [Freebuild] has disconnected
[BungeePluginMessages]: Message to playername: minecraft:register - [bungeecord:main, worldedit:cui, vanishnopacket:status]
[BungeePluginMessages]: Message to playername: minecraft:brand - Paper
[BungeePluginMessages]: Message from playername: minecraft:brand - vanilla


Fabric client, VoxelMap, WorldEditCUI:

[playername|/x.x.x.x:58999] <-> ServerConnector [Freebuild] has connected
Setting stored Location for playername: Freebuild
[/x.x.x.x:58999|playername] <-> DownstreamBridge <-> [Creative] has disconnected
[BungeePluginMessages]: Message to playername: minecraft:register - [bungeecord:main, worldedit:cui, vanishnopacket:status]
[BungeePluginMessages]: Message to playername: minecraft:brand - Paper
[BungeePluginMessages]: Message from playername: minecraft:brand - fabric
[BungeePluginMessages]: Message from playername: minecraft:register - [fabric:container/open, fabric-screen-handler-api-v1:open_screen, fabric:registry/sync, worldedit:cui]
[BungeePluginMessages]: Message from playername: minecraft:register - [worldinfo:world_id]


Plugin event handler code:

    @EventHandler
    public void onPluginMessage(PluginMessageEvent e) {
        if (e.getSender() instanceof ProxiedPlayer) {
            getLogger().info("Message from " + ((ProxiedPlayer) e.getSender()).getName() + ": " + e.getTag() + " - " + decode(e.getTag(), e.getData()));
        } else if (e.getReceiver() instanceof ProxiedPlayer) {
            getLogger().info("Message to " + ((ProxiedPlayer) e.getReceiver()).getName() + ": " + e.getTag() + " - " + decode(e.getTag(), e.getData()));
        }
    }
    
    private String decode(String tag, byte[] data) {
        if (tag.equals("minecraft:register") || tag.equals("minecraft:unregister")) {
            return Arrays.toString(new String(data, com.google.common.base.Charsets.UTF_8).split("\0"));
        }
        return new String(data, com.google.common.base.Charsets.UTF_8);
    }

**Comment by Janmm14** [comment]
I highly recommend to create an issue on BungeeCord for this in that case.

**Comment by dementisimus** [comment]
I always use the latest MC-Version. In this case it was MC 1.16.1 - Vanilla, no modified Client or so

**Comment by TNTUP** [comment]
I've seen that error when someone logs in with Geyser MC (Bedrock Edition to Java Edition proxy)

**Comment by ikuria** [comment]
> 
> 
> I created a plugin that logs those messages for debugging. The vanilla client definitely sends a minecraft:brand on server switch. Forge/Fabric clients also send one or more minecraft:register packets on server switch.
> 
> Vanilla Client:
> 
> [playername|/x.x.x.x:50282] <-> ServerConnector [Farmen] has connected
> Setting stored Location for playername: Farmen
> [/x.x.x.x:50282|playername] <-> DownstreamBridge <-> [Freebuild] has disconnected
> [BungeePluginMessages]: Message to playername: minecraft:register - [bungeecord:main, worldedit:cui, vanishnopacket:status]
> [BungeePluginMessages]: Message to playername: minecraft:brand - Paper
> [BungeePluginMessages]: Message from playername: minecraft:brand - vanilla
> 
> Fabric client, VoxelMap, WorldEditCUI:
> 
> [playername|/x.x.x.x:58999] <-> ServerConnector [Freebuild] has connected
> Setting stored Location for playername: Freebuild
> [/x.x.x.x:58999|playername] <-> DownstreamBridge <-> [Creative] has disconnected
> [BungeePluginMessages]: Message to playername: minecraft:register - [bungeecord:main, worldedit:cui, vanishnopacket:status]
> [BungeePluginMessages]: Message to playername: minecraft:brand - Paper
> [BungeePluginMessages]: Message from playername: minecraft:brand - fabric
> [BungeePluginMessages]: Message from playername: minecraft:register - [fabric:container/open, fabric-screen-handler-api-v1:open_screen, fabric:registry/sync, worldedit:cui]
> [BungeePluginMessages]: Message from playername: minecraft:register - [worldinfo:world_id]
> 
> Plugin event handler code:
> 
> ```
> @EventHandler
> public void onPluginMessage(PluginMessageEvent e) {
>     if (e.getSender() instanceof ProxiedPlayer) {
>         getLogger().info("Message from " + ((ProxiedPlayer) e.getSender()).getName() + ": " + e.getTag() + " - " + decode(e.getTag(), e.getData()));
>     } else if (e.getReceiver() instanceof ProxiedPlayer) {
>         getLogger().info("Message to " + ((ProxiedPlayer) e.getReceiver()).getName() + ": " + e.getTag() + " - " + decode(e.getTag(), e.getData()));
>     }
> }
> 
> private String decode(String tag, byte[] data) {
>     if (tag.equals("minecraft:register") || tag.equals("minecraft:unregister")) {
>         return Arrays.toString(new String(data, com.google.common.base.Charsets.UTF_8).split("\0"));
>     }
>     return new String(data, com.google.common.base.Charsets.UTF_8);
> }
> ```

need that plugin, because my server is doing same kicks with same error
waterfall 3.8.1

**Comment by ikuria** [comment]
still getting this error

**Comment by Janmm14** [comment]
Suggesting that the error should print out the registered channels.

**Comment by spamvictus** [comment]
I get this error too, but it seems like no one else has since there weren't any new new comments for months.
Well I would like to look into it codewise. If anybody of you guys reading this has some insights for me to find the bad boy in the code a bit easier... Please spill the beans for me :D

**Comment by Janmm14** [comment]
@spamvictus there's already a PR linked

**Comment by Chew** [comment]
There isn't a PR linked it looks like but probably referring to #572

**Comment by Brokkonaut** [comment]
We use that linked fix too, because otherwise players will get kicked after switching servers for some times.

**Comment by TNTUP** [comment]
Happens on BungeeCord aswell, https://paste.gg/p/anonymous/0ba10a3d550c412caf4fbd864b21039b

Probably because I'm on a 1.17 client (Fabric) on a 1.16.5 server w/ProtocolSupport & ViaVersion.

**Comment by andreasdc** [comment]
Is there any fix for what problem?

**Comment by Rigner** [comment]
I just PR'd a fix to the BungeeCord repo, with a whole rework of that relaying system, and how it should have been implemented in the first place. Hope it will be merged.

**Comment by andreasdc** [comment]
> I just PR'd a fix to the BungeeCord repo, with a whole rework of that relaying system, and how it should have been implemented in the first place. Hope it will be merged.

Did you test it?

**Comment by Rigner** [comment]
Yes I did, everything seemed fine.

Edit: Has been heavily tested. Couldn't reproduce that issue anymore.

**Comment by Rigner** [comment]
My PR has been merged on the BungeeCord repository. Just need to update upstream here.
