### ISSUE TITLE
1.16.2 support

### ISSUE THREAD

**Issue by Glucy-2** [PaperMC/Waterfall#559]
When I tried to connect a 1.16.2 server with waterfall#367, an error occured.
````java
[02:30:02 INFO]: [/180.*.*.78:19374] <-> InitialHandler has connected
[02:30:02 INFO]: [MAX_XiaoKui|/180.*.*.78:19374] <-> ServerConnector [survival] has connected
[02:30:03 WARN]: [MAX_XiaoKui|/180.*.*.78:19374] <-> ServerConnector [survival] - bad packet ID, are mods in use!? Unsupported protocol version 751
[02:30:03 INFO]: [MAX_XiaoKui] disconnected with: Exception Connecting:FastDecoderException : Error decoding packet id 24 with contents:
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 24 00 00 01 00 00 00 ff 03 13 6d 69 6e 65 63 72 |$.........minecr|
|00000010| 61 66 74 3a 6f 76 65 72 77 6f 72 6c 64 14 6d 69 |aft:overworld.mi|
............
|00007860| 69 6e 65 63 72 61 66 74 3a 6f 76 65 72 77 6f 72 |inecraft:overwor|
|00007870| 6c 64 14 4e 99 af 46 88 19 57 10 08 00 01 00 00 |ld.N..F..W......|
+--------+-------------------------------------------------+----------------+
[02:30:03 ERROR]: [/180.102.122.78:19374|MAX_XiaoKui] -> UpstreamBridge - encountered exception
>io.netty.handler.codec.EncoderException: net.md_5.bungee.protocol.OverflowPacketException: Cannot send string longer than Short.MAX_VALUE (got 153513 characters)
at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:125) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1025) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:294) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at net.md_5.bungee.netty.ChannelWrapper.close(ChannelWrapper.java:83) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at net.md_5.bungee.UserConnection.disconnect0(UserConnection.java:422) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at net.md_5.bungee.UserConnection.disconnect(UserConnection.java:398) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at net.md_5.bungee.ServerConnector.exception(ServerConnector.java:88) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at net.md_5.bungee.netty.HandlerBoss.exceptionCaught(HandlerBoss.java:177) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:281) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.AbstractChannelHandlerContext.fireExceptionCaught(AbstractChannelHandlerContext.java:273) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.ChannelInboundHandlerAdapter.exceptionCaught(ChannelInboundHandlerAdapter.java:143) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:381) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:311) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:425) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:792) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
>Caused by: net.md_5.bungee.protocol.OverflowPacketException: Cannot send string longer than Short.MAX_VALUE (got 153513 characters)
at net.md_5.bungee.protocol.DefinedPacket.writeString(DefinedPacket.java:21) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at net.md_5.bungee.protocol.packet.Kick.write(Kick.java:29) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at net.md_5.bungee.protocol.DefinedPacket.write(DefinedPacket.java:251) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:24) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at net.md_5.bungee.protocol.MinecraftEncoder.encode(MinecraftEncoder.java:9) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107) ~[waterfall-367.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:dcea0c1:367]
... 45 more
[02:30:03 INFO]: [/180.*.*.78:19374|MAX_XiaoKui] -> UpstreamBridge has disconnected
[02:30:03 INFO]: [MAX_XiaoKui|/180.*.*.78:19374] <-> ServerConnector [survival] has disconnected
````

**Comment by LemonCaramel** [comment]
Waterfall does not support 1.16.2 yet.

**Comment by tomcraft** [comment]
bungeecord and waterfall are not 1.16.2 compatible yet
