### ISSUE TITLE
Error with WaterFall when loading it for the first time

### ISSUE THREAD

**Issue by zxcvbnmasdfghjk7** [PaperMC/Waterfall#588]
Step 1: Put WaterFall.jar in a folder with no files except Waterfall.jar
Step: 2: Run Waterfall.jar

Error Log: 
[22:53:08 ERROR]: Exception in thread "main" java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.Map (java.lang.String and java.util.Map are in module java.base of loader 'bootstrap')
[22:53:08 ERROR]: 	at net.md_5.bungee.conf.YamlConfig.getListeners(YamlConfig.java:264)
[22:53:08 ERROR]: 	at net.md_5.bungee.conf.Configuration.load(Configuration.java:92)
[22:53:08 ERROR]: 	at io.github.waterfallmc.waterfall.conf.WaterfallConfiguration.load(WaterfallConfiguration.java:50)
[22:53:08 ERROR]: 	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:278)
[22:53:08 ERROR]: 	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
[22:53:08 ERROR]: 	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

Server Version:
Minecraft Version: 1.16.4
Build: #314

**Comment by electronicboy** [comment]
cannot reproduce, and, as this file is produced programmatically, meaning that in order to load off the disk, it must have been ran before, (either that or you're using some broken control panel or something). That error generally implies that your config.yml is mangled
