### ISSUE TITLE
the server you were previously on went down, you have been connected to a fallback server

### ISSUE THREAD

**Issue by Jake4-CX** [PaperMC/Waterfall#611]
Hello, I'm currently experiencing a problem when I switch servers from my 1.16.5 Survival server to my 1.8 Lobby (w/ Via Version on the proxy).

This happens roughly around 1 out of 4 attempts I switch server (From Survival to Lobby) and sometimes there's an error in console regarding this but there have been multiple times without an error provided.

This happens on both Waterfall versions I have tested (The lastest release 395, and release 393).

This error looks like it's related to [this closed Issue request](https://github.com/PaperMC/Waterfall/issues/608) from 6 days ago.

**Proxy Plugins:**
![image](https://user-images.githubusercontent.com/14060724/107939369-87cf3c00-6f7e-11eb-911e-458b2fdc2411.png)

**Lobby Plugins:**
![image](https://user-images.githubusercontent.com/14060724/107939393-8e5db380-6f7e-11eb-82f9-e3ac8f777da0.png)

**Survival (1.16.5) Plugins:**
![image](https://user-images.githubusercontent.com/14060724/107939423-974e8500-6f7e-11eb-8f8b-b3c10b8a9d15.png)

**Disconnect Message:**
`the the server you were previously on went down, you have been connected to a fallback server`

**Error in console:**

```java
[11:56:35] [Thread-16/WARN]: Event ServerConnectEvent(player=Jake4, target=BungeeServerInfo(name=Lobby-01, socketAddress=/SERVER_IP_RETRACTED, restricted=true), reason=PLUGIN, request=net.md_5.bungee.api.ServerConnectRequest@1986359d, cancelled=false) took 1,143ms to process!
[11:56:35] [Netty Worker IO Thread #46/ERROR]: [/PLAYER_IP_RETRACTED|Jake4] <-> DownstreamBridge <-> [Survival-01] - encountered exception
java.lang.IndexOutOfBoundsException: readerIndex(55) + length(1) exceeds writerIndex(55): PooledUnsafeDirectByteBuf(ridx: 55, widx: 55, cap: 55)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1478) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:732) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
	at io.netty.buffer.AbstractByteBuf.readUnsignedByte(AbstractByteBuf.java:746) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
	at net.md_5.bungee.entitymap.EntityMap.rewriteMetaVarInt(EntityMap.java:160) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
	at net.md_5.bungee.entitymap.EntityMap_1_16_2.rewriteClientbound(EntityMap_1_16_2.java:150) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
	at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:147) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
	at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:113) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:475) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-1.16-393.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:2eae08f:393]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
[11:56:35] [Netty Worker IO Thread #46/INFO]: [Jake4] disconnected with: The server you were previously on went down, you have been connected to a fallback server
[11:56:35] [Netty Worker IO Thread #46/INFO]: [/PLAYER_IP_RETRACTED|Jake4] -> UpstreamBridge has disconnected
[11:56:35] [Netty Worker IO Thread #46/INFO]: [/PLAYER_IP_RETRACTED|Jake4] <-> DownstreamBridge <-> [Survival-01] has disconnected
[11:56:35] [Netty Worker IO Thread #46/INFO]: [Jake4|/PLAYER_IP_RETRACTED] <-> ServerConnector [Lobby-01] has connected
[11:56:35] [Netty Worker IO Thread #46/WARN]: No client connected for pending server!
[11:56:35] [Netty Worker IO Thread #46/INFO]: [Jake4|/PLAYER_IP_RETRACTED] <-> ServerConnector [Lobby-01] has disconnected
```

**Comment by electronicboy** [comment]
We don't support protocol hacks, that exception also generally states that you had invalid entity metadata, either a bungeecord issue (which you'd need to reproduce on a 1.16 server and provide instructions), or an issue with your protocol hack or some plugin hiding behind it
