### ISSUE TITLE
Login questions

### ISSUE THREAD

**Issue by Hikari0964** [PaperMC/Waterfall#621]
[09:29:20 INFO]: [/127.0.0.1:58763] <-> InitialHandler has pinged
[09:29:24 INFO]: [/127.0.0.1:58764] <-> InitialHandler has connected
[09:29:24 WARN] [io.netty.util.concurrent.AbstractEventExecutor]: A task raised an exception. Task: net.md_5.bungee.connection.InitialHandler$6$1@2f3eb76d
java.lang.ClassCastException: java.util.LinkedHashMap incompatible with java.util.Collection
        at net.md_5.bungee.conf.YamlConfig.getPermissions(YamlConfig.java:329) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
        at net.md_5.bungee.UserConnection.addGroups(UserConnection.java:550) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
        at net.md_5.bungee.UserConnection.init(UserConnection.java:168) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
        at net.md_5.bungee.connection.InitialHandler$6$1.run(InitialHandler.java:549) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-1.16-403.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:7395ab3:403]
        at java.lang.Thread.run(Thread.java:823) [?:1.8.0_292]

**Comment by electronicboy** [comment]
your configuration is invalid, I recommend using a proper perm plugin in general, e.g. LuckPerms

**Comment by Janmm14** [comment]
Your permissions configuration is wrong

**Comment by Hikari0964** [comment]
Ok.
