### ISSUE TITLE
Can't start waterfall

### ISSUE THREAD

**Issue by JustLonelyy** [PaperMC/Waterfall#674]
I'm using latest waterfall version

[12:51:02 ERROR]: Exception in thread "main" java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to java.util.Collection
[12:51:02 ERROR]:       at net.md_5.bungee.conf.YamlConfig.getListeners(YamlConfig.java:245)
[12:51:02 ERROR]:       at net.md_5.bungee.conf.Configuration.load(Configuration.java:92)
[12:51:02 ERROR]:       at io.github.waterfallmc.waterfall.conf.WaterfallConfiguration.load(WaterfallConfiguration.java:50)
[12:51:02 ERROR]:       at net.md_5.bungee.BungeeCord.start(BungeeCord.java:279)
[12:51:02 ERROR]:       at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
[12:51:02 ERROR]:       at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

**Comment by Janmm14** [comment]
Invalid config.yml
