### ISSUE TITLE
Console spam upon joining the server

### ISSUE THREAD

**Issue by DangerMage** [PaperMC/Waterfall#684]
Whenever someone joins our fabric server and forge is enabled on waterfall we get this spam:

[10:45:21] [Server thread/INFO]: StormyIceLeopard joined the game
[10:45:21] [Netty Epoll Server IO #2/WARN]: Received invalid channel identifier "legacy:fml|hs" from connection net.minecraft.class_2535@34ec949f
net.minecraft.class_151: Non [a-z0-9/._-] character in path of location: legacy:fml|hs
        at net.minecraft.class_2960.<init>(class_2960.java:41) ~[intermediary-server.jar:?]
        at net.minecraft.class_2960.<init>(class_2960.java:46) ~[intermediary-server.jar:?]
        at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.addId(AbstractChanneledNetworkAddon.java:198) [0449379b-d44b-4c6c-bee4-3aa0d8a77e78.jar:?]
        at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.receiveRegistration(AbstractChanneledNetworkAddon.java:152) [0449379b-d44b-4c6c-bee4-3aa0d8a77e78.jar:?]
        at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:82) [0449379b-d44b-4c6c-bee4-3aa0d8a77e78.jar:?]
        at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.handle(ServerPlayNetworkAddon.java:84) [0449379b-d44b-4c6c-bee4-3aa0d8a77e78.jar:?]
        at net.minecraft.class_3244.handler$bbg000$handleCustomPayloadReceivedAsync(class_3244.java:1666) [intermediary-server.jar:?]
        at net.minecraft.class_3244.method_12075(class_3244.java) [intermediary-server.jar:?]
        at net.minecraft.class_2817.method_12199(class_2817.java:44) [intermediary-server.jar:?]
        at net.minecraft.class_2817.method_11054(class_2817.java:9) [intermediary-server.jar:?]
        at net.minecraft.class_2535.method_10759(class_2535.java:156) [intermediary-server.jar:?]
        at net.minecraft.class_2535.method_10770(class_2535.java:147) [intermediary-server.jar:?]
        at net.minecraft.class_2535.channelRead0(class_2535.java:52) [intermediary-server.jar:?]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [intermediary-server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [intermediary-server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [intermediary-server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [intermediary-server.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [intermediary-server.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [intermediary-server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [intermediary-server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [intermediary-server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [intermediary-server.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [intermediary-server.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [intermediary-server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [intermediary-server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [intermediary-server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [intermediary-server.jar:?]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [intermediary-server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [intermediary-server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [intermediary-server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [intermediary-server.jar:?]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [intermediary-server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [intermediary-server.jar:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [intermediary-server.jar:?]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [intermediary-server.jar:?]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:808) [intermediary-server.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:408) [intermediary-server.jar:?]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:308) [intermediary-server.jar:?]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [intermediary-server.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
[10:45:48] [Server thread/INFO]: StormyIceLeopard lost connection: Disconnected
[10:45:48] [Server thread/INFO]: StormyIceLeopard left the game

This doesn't happen when forge is disabled, but then of course we can't join forge servers which is a small problem since we have a forge and a fabric server

**Comment by electronicboy** [comment]
This is down to ViaVersion translating legacy plugin channel names to invalid keys

**Comment by StormyIceLeopard** [comment]
Neither the forge server or the fabric server has ViaVersion.

**Comment by electronicboy** [comment]
That error blatantly includes the hallmarks of being passed through via

**Comment by DangerMage** [comment]
> 
> 
> That error blatantly includes the hallmarks of being passed through via

Unless fabric proxy mod has via version in it, which i highly doubt, then we do not have via version

**Comment by StormyIceLeopard** [comment]
Our Lobby server has ViaVersion, but we have the Waterfall `config.yml` setup so when you connect with a specific subdomain you are connected directly to that server (bypassing/skipping lobby). `forced_hosts` feature

**Comment by astei** [comment]
> That error blatantly includes the hallmarks of being passed through via

No, this is [a bug in upstream BungeeCord](https://github.com/SpigotMC/BungeeCord/blob/8d783aa172830f212baa197b6b0c1c3d5f1237d1/protocol/src/main/java/net/md_5/bungee/protocol/packet/PluginMessage.java#L26). `FML|HS` is obviously not a valid Minecraft identifier, and `legacy:fml|hs` even less so.

This is likely the result of (a) a plugin registering the channel in question or (b) connecting to a server running 1.13+ using Forge for 1.12.2 or earlier, and having a plugin like ViaVersion on the proxy (or server) rewriting channel names.

Velocity does [drop the invalid characters](https://github.com/VelocityPowered/Velocity/blob/dev/3.0.0/proxy/src/main/java/com/velocitypowered/proxy/protocol/util/PluginMessageUtil.java#L165) when rewriting legacy channel names, though.

**Comment by electronicboy** [comment]
I forgot about that horror, but, generally expected via or some proto hack to be involved here given that there wouldn't be anything tryna send that on a 1.13+ server, nothing on the proxy would send that message on its own
