### ISSUE TITLE
LowMemorySet java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by luis-guideti** [PaperMC/Waterfall#86]
This error is probably because of some scoreboard configuration on spigot side, does **not** happens on all servers even tho they all have the same scoreboard and all run the same spigot build.

This error will disconnect the player on login and move him back to the lobby, you will be able to login on a second attempt 3/4 of the time.

Spigot 1.8.9 (Sorry, cant find the build numbers anymore)
Travertine (I compiled it yesterday, probably build 8, I removed a few debug logs I dislike so the line numbers may be wrong)

I have plenty of memory so I fixed for myself by removing the LowMemorySet, since I have build it myself you guys may want to fix it or just close this as not important, I am only reporting to help improve it.

Error reproduced with no plugins.

```
DownstreamBridge <-> [skyblock] - encountered exception
java.lang.ArrayIndexOutOfBoundsException: -3
    at java.util.ArrayList.elementData(Unknown Source)
    at java.util.ArrayList.remove(Unknown Source)
    at io.github.waterfallmc.waterfall.utils.LowMemorySet.remove(LowMemorySet.java:118)
    at net.md_5.bungee.api.score.Team.removePlayer(Team.java:38)
    at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:229)
    at net.md_5.bungee.protocol.packet.Team.handle(Team.java:151)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:75)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:350)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:372)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:358)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:610)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:551)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:465)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:437)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
    at java.lang.Thread.run(Unknown Source)
```

**Comment by Techcable** [comment]
The issue is that we don't check for a negative `indexOf` [in the remove method](https://github.com/WaterfallMC/Waterfall/blob/master/BungeeCord-Patches/0031-Reduce-the-overhead-of-lots-and-lots-of-teams-with-t.patch#L135). We assume that the key is present in the set, which it isn't necessarily.
